-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  achievement_code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category character varying CHECK (category::text = ANY (ARRAY['wins'::character varying, 'streak'::character varying, 'social'::character varying, 'rank'::character varying, 'special'::character varying, 'tournament'::character varying, 'ai'::character varying]::text[])),
  requirement_type character varying,
  requirement_value integer,
  reward_coins integer DEFAULT 0,
  reward_gems integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin (
  user_id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'readonly'::admin_role,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_active_at timestamp with time zone,
  CONSTRAINT admin_pkey PRIMARY KEY (user_id),
  CONSTRAINT admin_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  is_broadcast boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notifications_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin(user_id)
);
CREATE TABLE public.ai_analysis_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  user_id uuid NOT NULL,
  analysis_type character varying NOT NULL CHECK (analysis_type::text = ANY (ARRAY['post_match'::character varying, 'mid_game'::character varying, 'request_hint'::character varying]::text[])),
  ai_model character varying,
  overall_rating character varying CHECK ((overall_rating::text = ANY (ARRAY['excellent'::character varying, 'good'::character varying, 'average'::character varying, 'poor'::character varying]::text[])) OR overall_rating IS NULL),
  key_mistakes jsonb,
  best_moves jsonb,
  suggested_improvements text,
  win_probability_timeline jsonb,
  analysis_duration_ms integer,
  tokens_used integer,
  cost_cents integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_analysis_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_analysis_logs_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT ai_analysis_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.appeals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reason text NOT NULL CHECK (length(TRIM(BOTH FROM reason)) > 0),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::appeal_status,
  admin_response text CHECK (length(admin_response) <= 2000),
  processed_by uuid,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT appeals_pkey PRIMARY KEY (id),
  CONSTRAINT appeals_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id),
  CONSTRAINT appeals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT appeals_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text, 'SELECT'::text])),
  record_id uuid,
  user_id uuid,
  admin_user_id uuid,
  changes jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.categories (
  id text NOT NULL,
  name_vi text NOT NULL,
  name_en text,
  description text,
  icon text,
  color text DEFAULT '#22D3EE'::text,
  parent_category text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  max_equipped integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_user_id uuid NOT NULL,
  room_id uuid,
  match_id uuid,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'emote'::character varying, 'system'::character varying, 'sticker'::character varying]::text[])),
  content text NOT NULL CHECK (length(TRIM(BOTH FROM content)) > 0),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  channel_scope character varying DEFAULT 'global'::character varying CHECK (channel_scope::text = ANY (ARRAY['global'::character varying, 'friends'::character varying, 'room'::character varying, 'match'::character varying]::text[])),
  target_user_id uuid,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT chat_messages_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT chat_messages_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.currency_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_code character varying NOT NULL UNIQUE,
  name_vi character varying NOT NULL,
  name_en character varying,
  description_vi text,
  description_en text,
  currency_type character varying NOT NULL CHECK (currency_type::text = ANY (ARRAY['coin'::character varying, 'gem'::character varying]::text[])),
  amount integer NOT NULL CHECK (amount > 0),
  bonus_amount integer DEFAULT 0 CHECK (bonus_amount >= 0),
  price_vnd integer NOT NULL CHECK (price_vnd > 0),
  discount_percent integer DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
  original_price_vnd integer,
  icon_url text,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  max_purchases_per_user integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT currency_packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.currency_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  package_id uuid NOT NULL,
  txn_ref character varying NOT NULL UNIQUE,
  currency_type character varying NOT NULL CHECK (currency_type::text = ANY (ARRAY['coin'::character varying, 'gem'::character varying]::text[])),
  amount integer NOT NULL,
  bonus_amount integer DEFAULT 0,
  total_amount integer NOT NULL,
  price_vnd integer NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_method character varying DEFAULT 'vnpay'::character varying,
  vnp_data jsonb,
  balance_before integer,
  balance_after integer,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT currency_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT currency_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT currency_purchases_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.currency_packages(id)
);
CREATE TABLE public.friends (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  friend_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'blocked'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT friends_pkey PRIMARY KEY (id),
  CONSTRAINT friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES auth.users(id)
);
CREATE TABLE public.friendships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  friend_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'blocked'::character varying, 'rejected'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT friendships_pkey PRIMARY KEY (id),
  CONSTRAINT friendships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT friendships_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category character varying,
  price_coins integer DEFAULT 0,
  price_gems integer DEFAULT 0,
  is_premium boolean DEFAULT false,
  rarity character varying CHECK (rarity::text = ANY (ARRAY['common'::character varying, 'rare'::character varying, 'epic'::character varying, 'legendary'::character varying]::text[])),
  preview_url text,
  asset_data jsonb,
  is_available boolean DEFAULT true,
  release_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  source_type text DEFAULT 'shop'::text CHECK (source_type = ANY (ARRAY['shop'::text, 'achievement'::text, 'quest'::text, 'event'::text, 'gift'::text, 'starter'::text])),
  name_en text,
  description_en text,
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_items_category FOREIGN KEY (category) REFERENCES public.categories(id)
);
CREATE TABLE public.logs_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  cost_credits integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT logs_usage_pkey PRIMARY KEY (id),
  CONSTRAINT logs_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.match_replays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL UNIQUE,
  total_turns integer,
  replay_url text,
  is_public boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  view_count integer DEFAULT 0,
  download_count integer DEFAULT 0,
  rating numeric CHECK (rating IS NULL OR rating >= 0::numeric AND rating <= 5::numeric),
  rating_count integer DEFAULT 0,
  ai_analyzed boolean DEFAULT false,
  game_quality character varying CHECK ((game_quality::text = ANY (ARRAY['excellent'::character varying, 'good'::character varying, 'average'::character varying]::text[])) OR game_quality IS NULL),
  highlight_moves jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_replays_pkey PRIMARY KEY (id),
  CONSTRAINT match_replays_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.match_skill_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  user_id uuid NOT NULL,
  turn_number integer NOT NULL CHECK (turn_number > 0),
  offered_skills jsonb NOT NULL,
  selected_skill_id uuid,
  was_skipped boolean DEFAULT false,
  target_position jsonb,
  effect_result jsonb,
  board_state_before jsonb,
  board_state_after jsonb,
  selection_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_skill_logs_pkey PRIMARY KEY (id),
  CONSTRAINT match_skill_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT match_skill_logs_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_skill_logs_selected_skill_id_fkey FOREIGN KEY (selected_skill_id) REFERENCES public.skills(id)
);
CREATE TABLE public.match_skill_state (
  match_id uuid NOT NULL,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_skill_state_pkey PRIMARY KEY (match_id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid,
  match_type character varying NOT NULL DEFAULT 'casual'::character varying CHECK (match_type::text = ANY (ARRAY['casual'::character varying, 'ranked'::character varying, 'tournament'::character varying, 'friend'::character varying, 'ai'::character varying]::text[])),
  player_x_user_id uuid NOT NULL,
  player_o_user_id uuid,
  winner_user_id uuid,
  result character varying CHECK ((result::text = ANY (ARRAY['win_x'::character varying, 'win_o'::character varying, 'draw'::character varying, 'abandoned'::character varying]::text[])) OR result IS NULL),
  win_condition character varying,
  total_moves integer DEFAULT 0 CHECK (total_moves >= 0),
  duration_seconds integer CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
  avg_move_time numeric,
  player_x_mindpoint_change integer DEFAULT 0,
  player_o_mindpoint_change integer DEFAULT 0,
  board_size integer DEFAULT 15,
  win_length integer DEFAULT 5,
  final_board_state jsonb,
  is_ai_match boolean DEFAULT false,
  ai_difficulty character varying CHECK ((ai_difficulty::text = ANY (ARRAY['nhap_mon'::character varying, 'ky_tai'::character varying, 'nghich_thien'::character varying]::text[])) OR ai_difficulty IS NULL),
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  series_id uuid,
  game_number integer CHECK (game_number IS NULL OR game_number >= 1 AND game_number <= 3),
  swap2_history jsonb,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT matches_player_x_user_id_fkey FOREIGN KEY (player_x_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT matches_player_o_user_id_fkey FOREIGN KEY (player_o_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT matches_winner_user_id_fkey FOREIGN KEY (winner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT matches_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.ranked_series(id)
);
CREATE TABLE public.matchmaking_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  mode character varying NOT NULL CHECK (mode::text = ANY (ARRAY['rank'::character varying, 'casual'::character varying, 'tournament'::character varying]::text[])),
  elo_rating integer,
  current_rank character varying,
  joined_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'waiting'::character varying CHECK (status::text = ANY (ARRAY['waiting'::character varying, 'matched'::character varying, 'cancelled'::character varying]::text[])),
  matched_with_user_id uuid,
  room_id uuid,
  preferred_settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  matched_at timestamp with time zone,
  matched_with uuid,
  CONSTRAINT matchmaking_queue_pkey PRIMARY KEY (id),
  CONSTRAINT matchmaking_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT matchmaking_queue_matched_with_user_id_fkey FOREIGN KEY (matched_with_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT matchmaking_queue_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT matchmaking_queue_matched_with_fkey FOREIGN KEY (matched_with) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.moves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  player_user_id uuid NOT NULL,
  move_number integer NOT NULL CHECK (move_number > 0),
  position_x integer NOT NULL,
  position_y integer NOT NULL,
  time_taken integer,
  time_remaining integer,
  turn_player character varying CHECK ((turn_player::text = ANY (ARRAY['X'::character varying, 'O'::character varying]::text[])) OR turn_player IS NULL),
  action_type character varying DEFAULT 'normal_move'::character varying CHECK (action_type::text = ANY (ARRAY['normal_move'::character varying, 'skill_move'::character varying, 'undo'::character varying]::text[])),
  board_state_before jsonb,
  is_winning_move boolean DEFAULT false,
  skill_used character varying,
  skill_effect jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT moves_pkey PRIMARY KEY (id),
  CONSTRAINT moves_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT moves_player_user_id_fkey FOREIGN KEY (player_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['friend_request'::character varying, 'match_end'::character varying, 'achievement'::character varying, 'system'::character varying, 'tournament'::character varying, 'gift'::character varying]::text[])),
  title character varying,
  message text,
  is_read boolean DEFAULT false,
  related_id uuid,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  price_vnd integer NOT NULL,
  credits integer NOT NULL,
  owner_cut_percent numeric NOT NULL DEFAULT 40,
  metadata jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  package_id uuid,
  amount_vnd integer NOT NULL,
  credits_awarded integer DEFAULT 0,
  owner_cut_vnd integer DEFAULT 0,
  provider text DEFAULT 'vnpay'::text,
  provider_txid text,
  status text DEFAULT 'pending'::text,
  raw_payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT payments_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  username character varying CHECK (username::text ~ '^[a-zA-Z0-9_]{3,50}$'::text),
  display_name character varying,
  avatar_url text,
  settings jsonb DEFAULT '{}'::jsonb,
  current_rank character varying DEFAULT 'vo_danh'::character varying CHECK (current_rank::text = ANY (ARRAY['vo_danh'::character varying, 'tan_ky'::character varying, 'hoc_ky'::character varying, 'ky_lao'::character varying, 'cao_ky'::character varying, 'ky_thanh'::character varying, 'truyen_thuyet'::character varying]::text[])),
  mindpoint integer DEFAULT 0,
  elo_rating integer DEFAULT 1000 CHECK (elo_rating >= 0 AND elo_rating <= 5000),
  total_matches integer DEFAULT 0,
  total_wins integer DEFAULT 0,
  total_losses integer DEFAULT 0,
  total_draws integer DEFAULT 0,
  win_streak integer DEFAULT 0,
  best_win_streak integer DEFAULT 0,
  coins integer DEFAULT 0,
  gems integer DEFAULT 0,
  equipped_board_skin uuid,
  equipped_piece_skin uuid,
  equipped_avatar_frame uuid,
  last_active timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  level integer DEFAULT 1 CHECK (level >= 1 AND level <= 100),
  exp integer DEFAULT 0 CHECK (exp >= 0),
  metadata jsonb DEFAULT '{}'::jsonb,
  onboarding_completed boolean DEFAULT false,
  plan text DEFAULT 'free'::text,
  trial_expires_at timestamp with time zone,
  pro_expires_at timestamp with time zone,
  credits_balance integer DEFAULT 0,
  daily_ask_used integer DEFAULT 0,
  daily_analyze_used integer DEFAULT 0,
  daily_reset_at date,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rank_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  old_rank character varying,
  new_rank character varying NOT NULL,
  mindpoint integer NOT NULL,
  reason character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rank_history_pkey PRIMARY KEY (id),
  CONSTRAINT rank_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.ranked_series (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  player1_id uuid NOT NULL,
  player2_id uuid NOT NULL,
  player1_initial_mp integer NOT NULL DEFAULT 0,
  player2_initial_mp integer NOT NULL DEFAULT 0,
  player1_initial_rank character varying NOT NULL DEFAULT 'vo_danh'::character varying,
  player2_initial_rank character varying NOT NULL DEFAULT 'vo_danh'::character varying,
  player1_wins integer NOT NULL DEFAULT 0 CHECK (player1_wins >= 0 AND player1_wins <= 2),
  player2_wins integer NOT NULL DEFAULT 0 CHECK (player2_wins >= 0 AND player2_wins <= 2),
  games_to_win integer NOT NULL DEFAULT 2,
  current_game integer NOT NULL DEFAULT 1 CHECK (current_game >= 1 AND current_game <= 3),
  player1_side character NOT NULL DEFAULT 'X'::bpchar CHECK (player1_side = ANY (ARRAY['X'::bpchar, 'O'::bpchar])),
  player2_side character NOT NULL DEFAULT 'O'::bpchar CHECK (player2_side = ANY (ARRAY['X'::bpchar, 'O'::bpchar])),
  status character varying NOT NULL DEFAULT 'in_progress'::character varying CHECK (status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'abandoned'::character varying]::text[])),
  winner_id uuid,
  final_score character varying,
  winner_mp_change integer,
  loser_mp_change integer,
  winner_coins integer,
  loser_coins integer,
  winner_exp integer,
  loser_exp integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ranked_series_pkey PRIMARY KEY (id),
  CONSTRAINT ranked_series_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.profiles(user_id),
  CONSTRAINT ranked_series_player1_id_fkey FOREIGN KEY (player1_id) REFERENCES public.profiles(user_id),
  CONSTRAINT ranked_series_player2_id_fkey FOREIGN KEY (player2_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.report_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  admin_id uuid,
  action character varying NOT NULL CHECK (length(TRIM(BOTH FROM action)) > 0),
  old_status character varying,
  new_status character varying,
  notes text CHECK (length(notes) <= 2000),
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_actions_pkey PRIMARY KEY (id),
  CONSTRAINT report_actions_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id),
  CONSTRAINT report_actions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL,
  reported_user_id uuid,
  match_id uuid,
  type USER-DEFINED NOT NULL,
  description text CHECK (length(description) <= 1000),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::report_status,
  rule_analysis jsonb,
  reason_result text,
  ai_analysis jsonb,
  ai_summary_player text,
  ai_details_admin text,
  processed_at timestamp with time zone,
  processed_by uuid,
  admin_notes text CHECK (length(admin_notes) <= 2000),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(user_id),
  CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT reports_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT reports_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.room_players (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL,
  user_id uuid NOT NULL,
  player_side character varying CHECK ((player_side::text = ANY (ARRAY['X'::character varying, 'O'::character varying, 'team_a'::character varying, 'team_b'::character varying]::text[])) OR player_side IS NULL),
  player_order integer,
  is_ready boolean DEFAULT false,
  is_spectator boolean DEFAULT false,
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  CONSTRAINT room_players_pkey PRIMARY KEY (id),
  CONSTRAINT room_players_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT room_players_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_code character varying UNIQUE,
  owner_user_id uuid NOT NULL,
  room_name character varying,
  mode character varying NOT NULL DEFAULT 'casual'::character varying CHECK (mode::text = ANY (ARRAY['casual'::character varying, 'ranked'::character varying, 'tournament'::character varying, 'friend'::character varying]::text[])),
  is_private boolean DEFAULT false,
  invite_token character varying,
  max_players integer DEFAULT 2 CHECK (max_players >= 2 AND max_players <= 10),
  board_size integer DEFAULT 15 CHECK (board_size >= 10 AND board_size <= 25),
  win_length integer DEFAULT 5 CHECK (win_length >= 3 AND win_length <= 10),
  time_per_move integer DEFAULT 30,
  status character varying DEFAULT 'waiting'::character varying CHECK (status::text = ANY (ARRAY['waiting'::character varying, 'playing'::character varying, 'finished'::character varying]::text[])),
  current_players integer DEFAULT 1,
  game_config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  game_state jsonb DEFAULT jsonb_build_object('board', '[]'::jsonb, 'moves', '[]'::jsonb, 'currentTurn', 'X', 'currentGame', 1, 'scores', jsonb_build_object('X', 0, 'O', 0), 'gameStartedAt', NULL::unknown, 'lastMoveAt', NULL::unknown),
  swap2_enabled boolean DEFAULT false,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.seasons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  season_number integer NOT NULL UNIQUE,
  name character varying NOT NULL,
  name_en character varying,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  is_active boolean DEFAULT false,
  skill_pool jsonb NOT NULL DEFAULT '[]'::jsonb,
  theme_color character varying DEFAULT '#22D3EE'::character varying,
  banner_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seasons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.skill_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_code character varying NOT NULL UNIQUE,
  name_vi character varying NOT NULL,
  name_en character varying,
  description_vi text,
  description_en text,
  cards_count integer NOT NULL DEFAULT 5,
  common_rate numeric NOT NULL DEFAULT 0.7000,
  rare_rate numeric NOT NULL DEFAULT 0.2500,
  legendary_rate numeric NOT NULL DEFAULT 0.0500,
  price_tinh_thach integer DEFAULT 0,
  price_nguyen_than integer DEFAULT 0,
  source character varying NOT NULL DEFAULT 'shop'::character varying,
  is_active boolean DEFAULT true,
  icon_url text,
  background_color character varying DEFAULT '#ffffff'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT skill_packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  skill_code character varying NOT NULL UNIQUE,
  name_vi character varying NOT NULL,
  name_en character varying,
  description_vi text NOT NULL,
  description_en text,
  category USER-DEFINED NOT NULL,
  rarity USER-DEFINED NOT NULL DEFAULT 'common'::skill_rarity,
  effect_type character varying NOT NULL,
  effect_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  cooldown integer DEFAULT 3 CHECK (cooldown >= 0 AND cooldown <= 10),
  mana_cost integer DEFAULT 0,
  icon_url text,
  preview_animation character varying,
  effect_color character varying DEFAULT '#ffffff'::character varying,
  unlock_requirement jsonb,
  upgrade_costs jsonb DEFAULT '[{"coins": 500, "level": 2}, {"coins": 1500, "level": 3}]'::jsonb,
  level_scaling jsonb DEFAULT '{"2": 1.2, "3": 1.5}'::jsonb,
  is_active boolean DEFAULT true,
  is_starter boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT skills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.titles (
  id text NOT NULL,
  name_vi text NOT NULL,
  name_en text NOT NULL,
  description_vi text,
  description_en text,
  category text NOT NULL CHECK (category = ANY (ARRAY['rank'::text, 'wins'::text, 'streak'::text, 'special'::text, 'season'::text, 'social'::text, 'skill'::text, 'event'::text])),
  rarity text NOT NULL DEFAULT 'common'::text CHECK (rarity = ANY (ARRAY['common'::text, 'rare'::text, 'epic'::text, 'legendary'::text, 'mythic'::text])),
  icon text,
  color text DEFAULT '#22D3EE'::text,
  glow_color text,
  requirement_type text NOT NULL,
  requirement_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  points integer DEFAULT 0,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT titles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tournament_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  match_id uuid,
  round_number integer NOT NULL,
  match_number integer NOT NULL,
  bracket_path character varying CHECK ((bracket_path::text = ANY (ARRAY['winners'::character varying, 'losers'::character varying]::text[])) OR bracket_path IS NULL),
  player1_id uuid,
  player2_id uuid,
  winner_id uuid,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'bye'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournament_matches_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_matches_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT tournament_matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_matches_player1_id_fkey FOREIGN KEY (player1_id) REFERENCES public.tournament_players(id),
  CONSTRAINT tournament_matches_player2_id_fkey FOREIGN KEY (player2_id) REFERENCES public.tournament_players(id),
  CONSTRAINT tournament_matches_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.tournament_players(id)
);
CREATE TABLE public.tournament_players (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  user_id uuid NOT NULL,
  seed_number integer,
  bracket_position integer,
  current_round integer DEFAULT 1,
  status character varying DEFAULT 'registered'::character varying CHECK (status::text = ANY (ARRAY['registered'::character varying, 'active'::character varying, 'eliminated'::character varying, 'winner'::character varying]::text[])),
  placement integer,
  matches_played integer DEFAULT 0,
  matches_won integer DEFAULT 0,
  matches_lost integer DEFAULT 0,
  coins_earned integer DEFAULT 0,
  gems_earned integer DEFAULT 0,
  registered_at timestamp with time zone DEFAULT now(),
  eliminated_at timestamp with time zone,
  CONSTRAINT tournament_players_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_players_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_players_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.tournaments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_name character varying NOT NULL,
  tournament_code character varying UNIQUE,
  description text,
  creator_user_id uuid NOT NULL,
  format character varying NOT NULL CHECK (format::text = ANY (ARRAY['single_elimination'::character varying, 'double_elimination'::character varying, 'round_robin'::character varying]::text[])),
  min_players integer DEFAULT 4,
  max_players integer DEFAULT 32,
  current_players integer DEFAULT 0,
  board_size integer DEFAULT 15,
  win_length integer DEFAULT 5,
  time_per_move integer DEFAULT 30,
  game_config jsonb DEFAULT '{}'::jsonb,
  entry_fee_coins integer DEFAULT 0,
  entry_fee_gems integer DEFAULT 0,
  prize_pool_coins integer DEFAULT 0,
  prize_pool_gems integer DEFAULT 0,
  prize_distribution jsonb,
  status character varying DEFAULT 'registration'::character varying CHECK (status::text = ANY (ARRAY['registration'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  registration_start timestamp with time zone DEFAULT now(),
  registration_end timestamp with time zone,
  tournament_start timestamp with time zone,
  tournament_end timestamp with time zone,
  is_public boolean DEFAULT true,
  required_rank character varying,
  cover_image_url text,
  rules_text text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT tournaments_creator_user_id_fkey FOREIGN KEY (creator_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['earn'::character varying, 'spend'::character varying, 'reward'::character varying, 'refund'::character varying, 'admin_adjust'::character varying]::text[])),
  currency_type character varying NOT NULL CHECK (currency_type::text = ANY (ARRAY['coins'::character varying, 'gems'::character varying]::text[])),
  amount integer NOT NULL,
  balance_before integer NOT NULL,
  balance_after integer NOT NULL,
  reason character varying,
  related_entity_type character varying,
  related_entity_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  achievement_id uuid NOT NULL,
  progress integer DEFAULT 0 CHECK (progress >= 0),
  unlocked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id)
);
CREATE TABLE public.user_admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_admin_notifications_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.admin_notifications(id),
  CONSTRAINT user_admin_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_bans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  report_id uuid,
  ban_type USER-DEFINED NOT NULL,
  reason text NOT NULL CHECK (length(TRIM(BOTH FROM reason)) > 0),
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  lifted_at timestamp with time zone,
  lifted_by uuid,
  lift_reason text CHECK (length(lift_reason) <= 2000),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_bans_pkey PRIMARY KEY (id),
  CONSTRAINT user_bans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_bans_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id),
  CONSTRAINT user_bans_lifted_by_fkey FOREIGN KEY (lifted_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  item_id uuid NOT NULL,
  is_equipped boolean DEFAULT false,
  acquired_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_items_pkey PRIMARY KEY (id),
  CONSTRAINT user_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT user_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_package_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  package_id uuid NOT NULL,
  price_paid_tinh_thach integer DEFAULT 0,
  price_paid_nguyen_than integer DEFAULT 0,
  skills_received jsonb NOT NULL DEFAULT '[]'::jsonb,
  purchased_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_package_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT user_package_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_package_purchases_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.skill_packages(id)
);
CREATE TABLE public.user_skill_combos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  season_id uuid NOT NULL,
  preset_name character varying DEFAULT 'Default'::character varying,
  preset_slot integer DEFAULT 1 CHECK (preset_slot >= 1 AND preset_slot <= 3),
  skill_ids jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_array_length(skill_ids) <= 15),
  is_valid boolean DEFAULT true,
  validation_errors jsonb,
  is_active boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_skill_combos_pkey PRIMARY KEY (id),
  CONSTRAINT user_skill_combos_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_skill_combos_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id)
);
CREATE TABLE public.user_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  skill_id uuid NOT NULL,
  is_unlocked boolean DEFAULT false,
  unlocked_at timestamp with time zone,
  unlock_method character varying,
  current_level integer DEFAULT 1 CHECK (current_level >= 1 AND current_level <= 3),
  times_used integer DEFAULT 0,
  times_successful integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_skills_pkey PRIMARY KEY (id),
  CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);
CREATE TABLE public.user_titles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title_id text NOT NULL,
  unlocked_at timestamp with time zone DEFAULT now(),
  is_equipped boolean DEFAULT false,
  CONSTRAINT user_titles_pkey PRIMARY KEY (id),
  CONSTRAINT user_titles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_titles_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id)
);