import React, { createContext, useContext, useState, useEffect } from 'react'
import i18nData from '../i18n.json'

type Language = 'vi' | 'en' | 'zh' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, any>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Import translations from i18n.json
const i18nTranslations = i18nData as Record<Language, any>

// Legacy flat translations (kept for backward compatibility)
const translations: Record<Language, Record<string, string>> = {
  vi: {
        // Training modal
        'home.training.title': 'Phòng Thí Luyện',
        'home.training.subtitle': 'Chọn độ khó bot để luyện tập trước khi leo rank.',
        'home.training.nhapMon.title': 'Nhập Môn',
        'home.training.nhapMon.caption': 'Ưu tiên chặn nước mạnh',
        'home.training.kyTai.title': 'Kỳ Tài',
        'home.training.kyTai.caption': 'Cân bằng công thủ',
        'home.training.nghichThien.title': 'Nghịch Thiên',
        'home.training.nghichThien.caption': 'Luôn tìm cách tấn công',
        'home.training.thienTon.title': 'Thần Cảnh',
        'home.training.thienTon.caption': 'Nhìn trước 2 nước',
        'home.training.huVo.title': 'Hư Vô',
        'home.training.huVo.caption': 'Nhìn trước 3 nước',
        'home.training.difficultyEasy': 'Dễ',
        'home.training.difficultyMedium': 'Trung bình',
        'home.training.difficultyHard': 'Khó',
        'home.training.difficultyVeryHard': 'Rất khó',
        'home.training.difficultyMaster': 'Cao thủ',
        'home.training.createRoomBot': 'Tạo phòng & đấu bot',
      // Hotseat
      'hotseat.breadcrumb': 'Tiêu Dao',
      'hotseat.title': 'Tiêu Dao',
      'hotseat.subtitle': '1 máy 2 người',
      'hotseat.sideBlack': 'Quân Đen',
      'hotseat.sideWhite': 'Quân Trắng',
      'hotseat.turn': 'Lượt đi',
      'hotseat.startNewRoundBlackFirst': 'Chạm để bắt đầu ván mới, Quân Đen đi trước.',
      'hotseat.nextTurn': 'Tới lượt {name}',
      'hotseat.winThisRound': '{name} thắng ván này!',
      'hotseat.timeOutWin': '{loser} hết thời gian. {winner} thắng ván này!',
      'hotseat.setupTitle': 'Thiết lập trận',
      'hotseat.forbiddenRulesBlack': 'Cấm 3-3 / 4-4 cho Đen',
      'hotseat.timeLimit': 'Giới hạn thời gian',
      'hotseat.timePerTurn': 'Thời gian mỗi lượt',
      'hotseat.seconds': 'giây',
      'hotseat.swapSides': 'Đổi bên',
      'hotseat.newRound': 'Ván mới',
      'hotseat.resetScores': 'Xóa tỉ số',
      'hotseat.postWinTitle': 'Ván kết thúc',
      'hotseat.winThisRoundSuffix': 'thắng ván này!',
      'hotseat.review': 'Xem lại',
    // Navigation
    'nav.home': 'Trang Chủ',
    'nav.lobby': 'Phòng Chờ',
    'nav.shop': 'Cửa Hàng',
    'nav.profile': 'Tiểu Phụ',
    'nav.inventory': 'Kho Đồ',
    'nav.quests': 'Nhiệm Vụ',
    'nav.events': 'Sự Kiện',
    'nav.guide': 'Hướng Dẫn',
    'nav.logout': 'Đăng Xuất',
    
    // Breadcrumb
    'breadcrumb.home': 'Chánh Điện',
    'breadcrumb.profile': 'Tiên Phủ',
    
    // Home Navigation (for mobile menu)
    'home.nav.shop': 'Tiêu Bảo Các',
    'home.nav.badgeHot': 'HOT',
    'home.nav.badgeNew': 'MỚI',
    'home.nav.badgeRank': 'RANK',
    'home.nav.inventory': 'Túi Trữ Vật',
    'home.nav.quests': 'Tiên Duyên',
    'home.nav.events': 'Thiên Cơ Biến',
    'home.nav.khaiNhan': 'Khai Nhãn',
    'home.nav.guide': 'Bí Tịch',
    'home.nav.mentor': 'Cao Nhân Chỉ Điểm',
    
    // Home page
    'home.welcome': 'Chào mừng đến với Mindpoint Arena',
    'home.quickMatch': 'Tìm Trận Nhanh',
    'home.ranked': 'Rank',
    'home.training': 'Luyện Tập',
    'home.createRoom': 'Tạo Phòng',
    'home.hotseat': 'Chơi Local',
    'home.onlinePlayers': 'Người chơi online',
    'home.rank': 'Cấp bậc',
    'home.winRate': 'Tỷ lệ thắng',
    'home.totalMatches': 'Tổng số trận',
    
    // Home Hero Section
    'home.hero.title': 'VÔ DANH THÀNH VÔ ĐỐI',
    'home.hero.subtitle': '     Thủ kỳ lặng bóng vô danh\nHạ kỳ vạn trận thành danh muôn đời',
    'home.hero.ctaQuickMatch': 'GHÉP TRẬN NGAY',
    'home.hero.ctaRankNote': 'Rank',
    
    // Home Game Modes
    'home.modes.ranked': 'DỊ BIẾN KỲ',
    'home.modes.tournament': 'VẠN MÔN TRANH ĐẤU',
    'home.modes.training': 'THÍ LUYỆN',
    'home.modes.hotseat': 'KỲ TỰ TRẬN',
    // Home Events
    'home.events.thienCoBien.title': 'THIÊN CƠ BIẾN',
    'home.events.thienCoBien.subtitle': 'Sự kiện giải đấu lớn',
    'home.events.thienCoBien.chip': 'ĐẶC BIỆT',
    'home.events.thienCoBien.highlight': 'Thưởng x2 Mindpoint',
    'home.events.thienCoBien.timeline': '3 ngày còn lại',
    'home.events.thienCoBien.reward': '🏆 1000 Kim Cương',
    'home.events.thienCoBien.ctaLabel': 'Tham gia',
    'home.events.luaTraiDaiHoi.title': 'LỬA TRẠI ĐẠI HỘI',
    'home.events.luaTraiDaiHoi.subtitle': 'Đấu đội 3v3',
    'home.events.luaTraiDaiHoi.chip': 'MỚI',
    'home.events.luaTraiDaiHoi.highlight': 'Chế độ chơi mới',
    'home.events.luaTraiDaiHoi.timeline': '7 ngày còn lại',
    'home.events.luaTraiDaiHoi.reward': '💎 500 Gem + Skin',
    'home.events.luaTraiDaiHoi.ctaLabel': 'Khám phá',
    'home.events.tuyetDinhSongDau.title': 'TUYỆT ĐỈNH SONG ĐẤU',
    'home.events.tuyetDinhSongDau.subtitle': '1v1 vô địch',
    'home.events.tuyetDinhSongDau.chip': 'RANK',
    'home.events.tuyetDinhSongDau.highlight': 'Leo rank nhanh x3',
    'home.events.tuyetDinhSongDau.timeline': '5 ngày còn lại',
    'home.events.tuyetDinhSongDau.reward': '⭐ Top 1: 2000 Gem',
    'home.events.tuyetDinhSongDau.ctaLabel': 'Tham chiến',
    
    // Home Social Tabs
    'home.social.friends': 'Đạo Hữu',
    'home.social.chat': 'Truyền Âm',
    'home.social.info': 'Cao Nhân',
    
    // Home Friends
    'home.friends.title': 'Đạo Hữu',
    'home.friends.connections': '{count} kết nối',
    'home.friends.onlineCount': '{count} online',
    'home.friends.loading': 'Đang tải...',
    'home.friends.refresh': '🔄 Làm mới',
    'home.friends.searchPlaceholder': '🔍 Tìm đạo hữu...',
    'home.friends.filterAll': 'Tất cả',
    'home.friends.filterOnline': 'Online',
    'home.friends.filterIncoming': 'Lời mời đến',
    'home.friends.filterOutgoing': 'Đã gửi',
    'home.friends.challenge': 'Thách đấu',
    'home.friends.daysAgo': '{count} ngày trước',
    'home.friends.hoursAgo': '{count} giờ trước',
    'home.friends.minutesAgo': '{count} phút trước',
    'home.friends.justNow': 'Vừa xong',
    'home.friends.hidden': 'Ẩn',
    'home.friends.anonymousUser': 'Ẩn danh',
    'home.friends.anonymous': 'Vô danh',
    'home.friends.friendRequestSent': '{name} đã gửi lời mời kết bạn',
    'home.friends.friendRequestAccepted': '{name} đã chấp nhận lời mời',
    'home.friends.emptyStateAll': 'Chưa có đạo hữu nào',
    'home.friends.emptyStateOnline': 'Không có đạo hữu online',
    'home.friends.emptyStateIncoming': 'Không có lời mời đến',
    'home.friends.emptyStateOutgoing': 'Chưa gửi lời mời nào',
    
    // Profile
    'profile.overview': 'Kỳ Tịch',
    'profile.settings': 'Tiền Phủ',
    'profile.history': 'Lịch sử đấu',
    'profile.totalGames': 'Tổng quan',
    'profile.settingsTitle': 'Cài đặt',
    'profile.account': 'Tài khoản',
    'profile.ui': 'Giao diện',
    'profile.sound': 'Âm thanh',
    'profile.board': 'Bàn cờ & Nước đi',
    'profile.notifications': 'Thông báo',
    'profile.language': 'Ngôn ngữ',
    'profile.other': 'Khác',
    'profile.username': 'Tên người chơi',
    'profile.email': 'Email',
    'profile.changePassword': 'Đổi mật khẩu',
    'profile.theme': 'Giao diện',
    'profile.themeDark': 'Tối',
    'profile.themeLight': 'Sáng',
    'profile.uiEffects': 'Hiệu ứng UI',
    'profile.effectsQuality': 'Chất lượng hiệu ứng',
    'profile.effectsHigh': 'Cao',
    'profile.effectsMedium': 'Trung bình',
    'profile.effectsLow': 'Thấp',
    'profile.fontSize': 'Kích thước chữ',
    'profile.fontSmall': 'Nhỏ',
    'profile.fontMedium': 'Vừa',
    'profile.fontLarge': 'Lớn',
    'profile.sfx': 'Âm thanh hiệu ứng',
    'profile.bgMusic': 'Nhạc nền',
    'profile.volume': 'Âm lượng',
    'profile.highlightLastMove': 'Đánh dấu nước đi cuối',
    'profile.showWinningLine': 'Hiển thị đường thắng',
    'profile.pieceDropEffect': 'Hiệu ứng đặt quân',
    'profile.showHints': 'Hiển thị gợi ý',
    'profile.boardSkin': 'Giao diện bàn cờ',
    'profile.systemNotif': 'Thông báo hệ thống',
    'profile.inviteNotif': 'Lời mời đấu',
    'profile.chatNotif': 'Tin nhắn',
    'profile.turnNotif': 'Lượt đi',
    'profile.restoreDefaults': 'Khôi phục cài đặt gốc',
    
    // Shop
    'shop.title': 'Cửa Hàng',
    'shop.subtitle': 'Sưu tầm skin và vật phẩm độc quyền',
    'shop.coins': 'Tinh Thạch',
    'shop.gems': 'Nguyên Thần',
    'shop.featured': 'Nổi bật',
    'shop.avatars': 'Khung Avatar',
    'shop.boardSkins': 'Giao diện bàn cờ',
    'shop.emotes': 'Biểu cảm',
    'shop.buy': 'Mua',
    'shop.owned': 'Đã sở hữu',
    'shop.equipped': 'Đang dùng',
    'shop.free': 'Miễn phí',
    'shop.needLogin': 'Cần đăng nhập',
    'shop.loginMessage': 'Vui lòng đăng nhập để mua vật phẩm.',
    'shop.notEnoughCurrency': 'Không đủ tiền',
    'shop.notEnoughCurrencyMessage': 'Không đủ {currency} để mua vật phẩm này.',
    'shop.confirmPurchase': 'Xác nhận mua',
    'shop.confirmPurchaseMessage': 'Bạn chắc chắn muốn {action}?',
    'shop.purchaseSuccess': 'Mua thành công!',
    'shop.purchaseSuccessMessage': 'Đã mua {item}. Đi tới Inventory để sử dụng!',
    'shop.purchaseFailed': 'Mua thất bại',
    'shop.loading': 'Đang tải...',
    'shop.breadcrumbShop': 'Tiêu Bảo Các',
    'shop.yourBalance': 'Số dư của bạn',
    'shop.collection': 'Bộ sưu tập',
    
    // Quests
    'quests.title': 'Nhiệm Vụ',
    'quests.subtitle': 'Hoàn thành nhiệm vụ nhận thưởng hấp dẫn',
    'quests.daily': 'Hằng ngày',
    'quests.weekly': 'Hằng tuần',
    'quests.achievements': 'Thành tựu',
    'quests.progress': 'Tiến độ',
    'quests.claim': 'Nhận thưởng',
    'quests.completed': 'Hoàn thành',
    'quests.claimed': 'Đã nhận',
    'quests.rewards': 'Phần thưởng',
    'quests.exp': 'EXP',
    'quests.loading': 'Đang tải...',
    'quests.needLogin': 'Vui lòng đăng nhập để xem nhiệm vụ',
    'quests.levelProgress': 'Tiến độ cấp độ',
    'quests.currentLevel': 'Cấp hiện tại',
    'quests.nextLevel': 'Cấp tiếp theo',
    'quests.expNeeded': 'EXP cần thiết',
    'quests.claimSuccess': 'Nhận thưởng thành công!',
    'quests.claimSuccessMessage': 'Đã nhận {coins} Tinh Thạch{gems}!',
    'quests.difficultyEasy': 'Dễ',
    'quests.difficultyMedium': 'Trung bình',
    'quests.difficultyHard': 'Khó',
    'quests.difficultyVeryHard': 'Cực khó',
    
    // Events
    'events.title': 'Sự Kiện',
    'events.subtitle': 'Tham gia sự kiện nhận thưởng khủng',
    'events.current': 'Đang diễn ra',
    'events.upcoming': 'Sắp tới',
    'events.past': 'Đã kết thúc',
    'events.joinNow': 'Tham gia ngay',
    'events.viewDetails': 'Xem chi tiết',
    'events.loginEvent': 'Sự Kiện Đăng Nhập',
    'events.loginEventDesc': 'Đăng nhập mỗi ngày nhận thưởng',
    'events.matchEvent': 'Sự Kiện Chiến Đấu',
    'events.matchEventDesc': 'Chơi trận nhận Tinh Thạch và Gem',
    'events.specialEvent': 'Sự Kiện Đặc Biệt',
    'events.specialEventDesc': 'Săn Gem khủng cuối tuần',
    'events.consecutiveLogins': 'Đăng nhập liên tiếp',
    'events.todayMatches': 'Trận hôm nay',
    'events.day': 'Ngày',
    'events.matches': 'trận',
    'events.claimed': 'Đã nhận',
    'events.claimReward': 'Nhận thưởng',
    'events.needLogin': 'Vui lòng đăng nhập để tham gia sự kiện',
    'events.loading': 'Đang tải...',
    'events.notEligible': 'Bạn chưa đủ điều kiện nhận thưởng này!',
    'events.claimSuccess': 'Đã nhận {coins} Tinh Thạch{gems}!',
    'events.claimFailed': 'Lỗi khi nhận thưởng!',
    'events.needMatches': 'Bạn cần chơi',
    'events.dailyCheckin': 'Điểm Danh Hàng Ngày',
    'events.battleQuests': 'Nhiệm Vụ Chiến Đấu',
    'events.playMatches': 'Chơi {n} trận',
    'events.progress': 'Tiến độ',
    'events.locked': 'Chưa mở',
    'events.notEnough': 'Chưa đủ',
    'events.preparing': 'Đang chuẩn bị...',
    'events.dayN': 'Ngày {n}',
    'events.aboutGems': 'Về Gem',
    'events.aboutGemsDesc': 'Gem là tiền tệ cao cấp để mua vật phẩm hiếm và đổi Tinh Thạch.',
    
    // Guide
    'guide.title': 'Hướng Dẫn',
    'guide.subtitle': 'Học tập và trở thành cao thủ',
    'guide.mainTitle': 'THIÊN CƠ BÍ ĐIỂN',
    'guide.mainSubtitle': 'Tổng tập đạo caro trong MindPoint Arena',
    'guide.tableOfContents': 'Mục Lục',
    'guide.prevSection': 'Mục trước',
    'guide.nextSection': 'Mục tiếp',
    'guide.compact': 'Thu gọn',
    'guide.expand': 'Mở rộng',
    'guide.viewMore': 'Xem thêm',
    'guide.intro': 'Lời Ngỏ Từ Kỳ Môn',
    'guide.rules': 'Quy Luật Đấu Trận',
    'guide.tactics': 'Chiến Thuật Căn Bản',
    'guide.modes': 'Các Chế Độ Tu Luyện',
    'guide.progression': 'Hệ Thống Tu Luyện',
    'guide.advanced': 'Bí Kíp Cao Thủ',
    'guide.faq': 'Nghi Vấn Thường Gặp',
    'guide.breadcrumbGuide': 'Bí Tịch',
    'guide.menuIntro': 'Lời Ngỏ',
    'guide.menuRules': 'Quy Luật',
    'guide.menuTactics': 'Chiến Thuật',
    'guide.menuModes': 'Chế Độ',
    'guide.menuProgression': 'Tu Luyện',
    'guide.menuAdvanced': 'Bí Kíp',
    'guide.menuFaq': 'FAQ',
    // Guide Section Content (Intro)
    'guide.intro.subtitle1': 'Chào mừng tân đồ',
    'guide.intro.text1': 'Ta là trưởng lão Kỳ Môn, người canh giữ đạo caro trong thế giới MindPoint Arena. Ngươi đã bước chân vào một hành trình tu luyện đầy gian nan nhưng vinh quang.',
    'guide.intro.subtitle2': 'Đạo caro là gì?',
    'guide.intro.text2': 'Đạo caro không đơn thuần là trò chơi. Đó là môn kỳ thuật chiến thuật cao siêu, nơi mỗi nước đi là một bước tu hành, mỗi chiến thắng là một tầng đột phá.',
    'guide.intro.subtitle3': 'Mục tiêu của ngươi',
    'guide.intro.text3': 'Từ Vô Danh, ngươi sẽ trải qua nhiều cảnh giới và hun đúc bản lĩnh để vươn tới đỉnh phong.',
    // Rules
    'guide.rules.subtitle1': 'Luật cơ bản',
    'guide.rules.text1': 'Hai kỳ thủ lần lượt đặt quân. Ai tạo được 5 quân thẳng hàng (ngang, dọc, chéo) trước sẽ thắng.',
    'guide.rules.subtitle2': 'Kích thước bàn',
    'guide.rules.text2': 'Bàn chuẩn 15x15 phổ biến nhất. Bàn lớn hơn yêu cầu tầm nhìn chiến thuật sâu hơn.',
    'guide.rules.subtitle3': 'Thời gian suy nghĩ',
    'guide.rules.text3': 'Có thể giới hạn thời gian mỗi lượt và tổng trận để tăng áp lực thi đấu.',
    'guide.rules.subtitle4': 'Ưu tiên lượt đi',
    'guide.rules.text4': 'Bên đi trước có lợi thế khai cục nhưng phải tạo áp lực đủ mạnh để duy trì thế.',
    // Tactics
    'guide.tactics.subtitle1': 'Tạo song kiếm',
    'guide.tactics.text1': 'Tạo hai mối đe dọa thắng đồng thời buộc đối thủ chỉ chặn được một.',
    'guide.tactics.subtitle2': 'Phòng thủ chủ động',
    'guide.tactics.text2': 'Vừa tấn công vừa quan sát để chặn các chuỗi 3-4 nguy hiểm sớm.',
    'guide.tactics.subtitle3': 'Kiểm soát trung tâm',
    'guide.tactics.text3': 'Khu trung tâm mở ra nhiều hướng phát triển cho chuỗi tấn công.',
    'guide.tactics.subtitle4': 'Dụ địch',
    'guide.tactics.text4': 'Tạo thế giả đánh lạc hướng rồi triển khai nước thắng ở vị trí khác.',
    'guide.tactics.subtitle5': 'Liên hoàn kế',
    'guide.tactics.text5': 'Xây nhiều lớp đe dọa dự phòng để luôn còn đường thắng.',
    // Modes
    'guide.modes.subtitle1': 'Luyện tập với AI',
    'guide.modes.text1': 'Chọn độ khó để rèn phản xạ và đọc thế cờ trước khi leo rank.',
    'guide.modes.subtitle2': 'Đấu thường',
    'guide.modes.text2': 'Giao hữu không ảnh hưởng điểm, thích hợp thử chiến thuật mới.',
    'guide.modes.subtitle3': 'Xếp hạng',
    'guide.modes.text3': 'Mỗi trận ảnh hưởng điểm, leo bảng để khẳng định thực lực.',
    'guide.modes.subtitle4': 'Phòng riêng',
    'guide.modes.text4': 'Tùy chỉnh luật, mời bạn bè, luyện nhóm hiệu quả.',
    'guide.modes.subtitle5': 'Giải đấu',
    'guide.modes.text5': 'Cạnh tranh quy mô lớn với thưởng hấp dẫn.',
    // Progression
    'guide.progression.subtitle1': 'Rank & ELO',
    'guide.progression.text1': 'Điểm phản ánh thực lực, thắng đối thủ mạnh tăng nhiều hơn.',
    'guide.progression.subtitle2': 'Coin & Gem',
    'guide.progression.text2': 'Coin dễ kiếm, Gem hiếm dùng cho vật phẩm đặc biệt.',
    'guide.progression.subtitle3': 'Nhiệm vụ hằng ngày',
    'guide.progression.text3': 'Chuỗi nhiệm vụ nhỏ giúp duy trì tiến độ tài nguyên.',
    'guide.progression.subtitle4': 'Thành tựu',
    'guide.progression.text4': 'Mốc đặc biệt mở khóa danh hiệu và thưởng.',
    'guide.progression.subtitle5': 'Skin & Trang trí',
    'guide.progression.text5': 'Thể hiện phong cách qua skin bàn & quân.',
    // Advanced
    'guide.advanced.subtitle1': 'AI phân tích',
    'guide.advanced.text1': 'Xem lại nước đi tối ưu và sai lầm để cải thiện.',
    'guide.advanced.subtitle2': 'Replay & Học hỏi',
    'guide.advanced.text2': 'Phân tích ván cao thủ để học cấu trúc khai cuộc.',
    'guide.advanced.subtitle3': 'Bang hội & Bạn bè',
    'guide.advanced.text3': 'Luyện tập cùng nhóm tăng tốc tiến bộ.',
    'guide.advanced.subtitle4': 'Quản lý thời gian',
    'guide.advanced.text4': 'Ra quyết định nhanh giữ áp lực cho đối thủ.',
    'guide.advanced.subtitle5': 'Tâm lý thi đấu',
    'guide.advanced.text5': 'Giữ bình tĩnh trước chuỗi thua để phục hồi phong độ.',
    // FAQ
    'guide.faq.q1.title': 'Làm sao leo rank nhanh?',
    'guide.faq.q1.body': 'Chơi đều, phân tích sau trận, tránh lặp lại sai lầm. Chuỗi thắng cho thêm điểm.',
    'guide.faq.q2.title': 'Mất coin khi thua có sao không?',
    'guide.faq.q2.body': 'Chế độ thường không mất coin. Chỉ phòng đặt cược mới rủi ro.',
    'guide.faq.q3.title': 'AI phân tích có chính xác không?',
    'guide.faq.q3.body': 'Huấn luyện từ nhiều ván cao thủ, độ chính xác cao đặc biệt ở bàn chuẩn.',
    'guide.faq.q4.title': 'Đổi username ở đâu?',
    'guide.faq.q4.body': 'Trong phần Profile. Miễn phí lần đầu, các lần sau tốn Gem.',
    'guide.faq.q5.title': 'Kiếm Gem nhanh thế nào?',
    'guide.faq.q5.body': 'Thành tựu khó, nhiệm vụ tuần, giải đấu hoặc nạp.',
    
    // Lobby
    'lobby.title': 'Phòng Chờ',
    'lobby.findMatch': 'Tìm trận',
    'lobby.createRoom': 'Tạo phòng',
    'lobby.joinRoom': 'Vào phòng',
    'lobby.roomCode': 'Mã phòng',
    'lobby.searching': 'Đang tìm...',
    'lobby.cancel': 'Hủy',
    
    // Inventory
    'inventory.title': 'Bộ Sưu Tập',
    'inventory.subtitle': 'Quản lý và sử dụng các vật phẩm đã sở hữu',
    'inventory.search': 'Tìm kiếm...',
    'inventory.filterType': 'Loại vật phẩm',
    'inventory.filterRarity': 'Độ hiếm',
    'inventory.filterStatus': 'Trạng thái',
    'inventory.all': 'Tất cả',
    'inventory.rarityCommon': 'Thường',
    'inventory.rarityRare': 'Hiếm',
    'inventory.rarityEpic': 'Cao cấp',
    'inventory.rarityLegendary': 'Huyền thoại',
    'inventory.statusEquipped': 'Đang dùng',
    'inventory.statusUnequipped': 'Chưa dùng',
    'inventory.totalItems': 'Tổng vật phẩm',
    'inventory.breadcrumbHome': 'Chánh Điện',
    'inventory.breadcrumbInventory': 'Túi Trữ Vật',
    'inventory.yourCollection': 'Bộ sưu tập của bạn',
    'inventory.loading': 'Đang tải...',
    'inventory.pleaseLogin': 'Vui lòng đăng nhập',
    'inventory.toViewCollection': 'để xem bộ sưu tập của bạn',
    'inventory.noItems': 'Chưa có vật phẩm nào',
    'inventory.visitShop': 'Hãy ghé Shop để sắm đồ nhé!',
    'inventory.goToShop': 'Đi tới Shop',
    'inventory.use': 'Sử dụng',
    'inventory.using': 'Đang dùng',
    'inventory.acquired': 'Nhận',
    'inventory.modalSuccess': 'Thành công',
    'inventory.modalError': 'Lỗi',
    'inventory.modalNotification': 'Thông báo',
    'inventory.modalOk': 'Đồng ý',
    'inventory.errorPleaseLogin': 'Vui lòng đăng nhập',
    'inventory.errorAlreadyEquipped': 'Vật phẩm này đang được sử dụng',
    'inventory.successEquipped': 'Đã trang bị',
    'inventory.errorCannotUse': 'Không thể sử dụng vật phẩm',
    
    // Common
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.close': 'Đóng',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.ok': 'OK',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.level': 'Cấp',
    'common.exp': 'Kinh nghiệm',
    'common.wins': 'Thắng',
    'common.losses': 'Thua',
    'common.draws': 'Hòa',
    'common.and': 'và',
    
    // Settings Popup
    'settings.title': 'Cài đặt nhanh',
    'settings.subtitle': 'Điều chỉnh âm thanh & hiệu ứng',
    'settings.sfx': 'Âm thanh hiệu ứng',
    'settings.bgMusic': 'Nhạc nền',
    'settings.notification': 'Thông báo',
    'settings.language': 'Ngôn ngữ',
    'settings.effects': 'Hiệu ứng',
    'settings.effectsHigh': 'Cao',
    'settings.effectsMedium': 'Trung bình',
    'settings.effectsLow': 'Thấp',
    
    // Rank System
    'rank.label': 'Cảnh Giới',
    'rank.vo_danh': 'Vô Danh',
    'rank.tan_ky': 'Tân Kỳ',
    'rank.hoc_ky': 'Học Kỳ',
    'rank.ky_lao': 'Kỳ Lão',
    'rank.cao_ky': 'Cao Kỳ',
    'rank.ky_thanh': 'Kỳ Thánh',
    'rank.truyen_thuyet': 'Truyền Thuyết',
    
    // Auth Landing
    'auth.landing.subtitle': 'Hãy đăng nhập hoặc đăng ký để bắt đầu trận đấu',
    'auth.landing.login': 'ĐĂNG NHẬP',
    'auth.landing.signup': 'ĐĂNG KÝ',
  },
  
  en: {
        // Training modal
        'home.training.title': 'Training Hall',
        'home.training.subtitle': 'Choose bot difficulty to practice before climbing ranks.',
        'home.training.nhapMon.title': 'Beginner',
        'home.training.nhapMon.caption': 'Prioritize blocking strong threats',
        'home.training.kyTai.title': 'Prodigy',
        'home.training.kyTai.caption': 'Balanced offense and defense',
        'home.training.nghichThien.title': 'Heaven-Defying',
        'home.training.nghichThien.caption': 'Always look to attack',
        'home.training.thienTon.title': 'Divine Realm',
        'home.training.thienTon.caption': 'Look ahead 2 moves',
        'home.training.huVo.title': 'Void',
        'home.training.huVo.caption': 'Look ahead 3 moves',
        'home.training.difficultyEasy': 'Easy',
        'home.training.difficultyMedium': 'Medium',
        'home.training.difficultyHard': 'Hard',
        'home.training.difficultyVeryHard': 'Very Hard',
        'home.training.difficultyMaster': 'Master',
        'home.training.createRoomBot': 'Create room & fight bot',
      // Hotseat
      'hotseat.breadcrumb': 'Hotseat',
      'hotseat.title': 'Hotseat',
      'hotseat.subtitle': 'Two players, one device',
      'hotseat.sideBlack': 'Black',
      'hotseat.sideWhite': 'White',
      'hotseat.turn': 'Turn',
      'hotseat.startNewRoundBlackFirst': 'Tap to start a new round, Black goes first.',
      'hotseat.nextTurn': "{name}'s turn",
      'hotseat.winThisRound': '{name} wins this round!',
      'hotseat.timeOutWin': '{loser} ran out of time. {winner} wins this round!',
      'hotseat.setupTitle': 'Match Setup',
      'hotseat.forbiddenRulesBlack': 'Black forbidden: 3-3 / 4-4',
      'hotseat.timeLimit': 'Time limit',
      'hotseat.timePerTurn': 'Time per turn',
      'hotseat.seconds': 'seconds',
      'hotseat.swapSides': 'Swap sides',
      'hotseat.newRound': 'New round',
      'hotseat.resetScores': 'Reset scores',
      'hotseat.postWinTitle': 'Round Finished',
      'hotseat.winThisRoundSuffix': 'wins this round!',
      'hotseat.review': 'Review',
    // Navigation
    'nav.home': 'Home',
    'nav.lobby': 'Lobby',
    'nav.shop': 'Shop',
    'nav.profile': 'Profile',
    'nav.inventory': 'Inventory',
    'nav.quests': 'Quests',
    'nav.events': 'Events',
    'nav.guide': 'Guide',
    'nav.logout': 'Logout',
    
    // Breadcrumb
    'breadcrumb.home': 'Main Hall',
    'breadcrumb.profile': 'Immortal Palace',
    
    // Home Navigation (for mobile menu)
    'home.nav.shop': 'Shop',
    'home.nav.badgeHot': 'HOT',
    'home.nav.badgeNew': 'NEW',
    'home.nav.badgeRank': 'RANK',
    'home.nav.inventory': 'Inventory',
    'home.nav.quests': 'Quests',
    'home.nav.events': 'Events',
    'home.nav.khaiNhan': 'Rank',
    'home.nav.guide': 'Guide',
    'home.nav.mentor': 'Replay Analysis',
    
    // Home page
    'home.welcome': 'Welcome to Mindpoint Arena',
    'home.quickMatch': 'Quick Match',
    'home.ranked': 'Ranked',
    'home.training': 'Training',
    'home.createRoom': 'Create Room',
    'home.hotseat': 'Local Play',
    'home.onlinePlayers': 'Online players',
    'home.rank': 'Rank',
    'home.winRate': 'Win rate',
    'home.totalMatches': 'Total matches',
    
    // Home Hero Section
    'home.hero.title': 'FROM UNKNOWN TO UNBEATABLE',
    'home.hero.subtitle': 'Play now, improve every day - Your legend starts here',
    'home.hero.ctaQuickMatch': 'QUICK MATCH',
    'home.hero.ctaRankNote': 'Rank',
    
    // Home Game Modes
    'home.modes.ranked': 'RANKED ARENA',
    'home.modes.tournament': 'TOURNAMENT',
    'home.modes.training': 'TRAINING HALL',
    'home.modes.hotseat': 'LOCAL DUEL',
    
    // Home Events
    'home.events.thienCoBien.title': 'HEAVEN\'S GAMBIT',
    'home.events.thienCoBien.subtitle': 'Major Tournament',
    'home.events.thienCoBien.chip': 'SPECIAL',
    'home.events.thienCoBien.highlight': 'x2 Mindpoint Reward',
    'home.events.thienCoBien.timeline': '3 days left',
    'home.events.thienCoBien.reward': '🏆 1000 Diamonds',
    'home.events.thienCoBien.ctaLabel': 'Join Now',
    'home.events.luaTraiDaiHoi.title': 'CAMPFIRE GATHERING',
    'home.events.luaTraiDaiHoi.subtitle': '3v3 Team Battle',
    'home.events.luaTraiDaiHoi.chip': 'NEW',
    'home.events.luaTraiDaiHoi.highlight': 'New Game Mode',
    'home.events.luaTraiDaiHoi.timeline': '7 days left',
    'home.events.luaTraiDaiHoi.reward': '💎 500 Gems + Skin',
    'home.events.luaTraiDaiHoi.ctaLabel': 'Explore',
    'home.events.tuyetDinhSongDau.title': 'ULTIMATE DUEL',
    'home.events.tuyetDinhSongDau.subtitle': '1v1 Championship',
    'home.events.tuyetDinhSongDau.chip': 'RANKED',
    'home.events.tuyetDinhSongDau.highlight': 'x3 Rank Speed',
    'home.events.tuyetDinhSongDau.timeline': '5 days left',
    'home.events.tuyetDinhSongDau.reward': '⭐ Top 1: 2000 Gems',
    'home.events.tuyetDinhSongDau.ctaLabel': 'Join Battle',
    
    // Home Social Tabs
    'home.social.friends': 'Friends',
    'home.social.chat': 'Chat',
    'home.social.info': 'AI Guide',
    
    // Home Friends
    'home.friends.title': 'Friends',
    'home.friends.connections': '{count} connections',
    'home.friends.onlineCount': '{count} online',
    'home.friends.loading': 'Loading...',
    'home.friends.refresh': '🔄 Refresh',
    'home.friends.searchPlaceholder': '🔍 Search friends...',
    'home.friends.filterAll': 'All',
    'home.friends.filterOnline': 'Online',
    'home.friends.filterIncoming': 'Incoming',
    'home.friends.filterOutgoing': 'Sent',
    'home.friends.challenge': 'Challenge',
    'home.friends.daysAgo': '{count} days ago',
    'home.friends.hoursAgo': '{count} hours ago',
    'home.friends.minutesAgo': '{count} minutes ago',
    'home.friends.justNow': 'Just now',
    'home.friends.hidden': 'Hidden',
    'home.friends.anonymousUser': 'Anonymous',
    'home.friends.anonymous': 'Unknown',
    'home.friends.friendRequestSent': '{name} sent you a friend request',
    'home.friends.friendRequestAccepted': '{name} accepted your request',
    'home.friends.emptyStateAll': 'No friends yet',
    'home.friends.emptyStateOnline': 'No friends online',
    'home.friends.emptyStateIncoming': 'No incoming requests',
    'home.friends.emptyStateOutgoing': 'No sent requests',
    
    // Profile
    'profile.overview': 'Chronicles',
    'profile.settings': 'Settings',
    'profile.history': 'Match History',
    'profile.totalGames': 'Total Games',
    'profile.settingsTitle': 'Settings',
    'profile.account': 'Account',
    'profile.ui': 'Interface',
    'profile.sound': 'Sound',
    'profile.board': 'Board & Moves',
    'profile.notifications': 'Notifications',
    'profile.language': 'Language',
    'profile.other': 'Other',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.changePassword': 'Change Password',
    'profile.theme': 'Theme',
    'profile.themeDark': 'Dark',
    'profile.themeLight': 'Light',
    'profile.uiEffects': 'UI Effects',
    'profile.effectsQuality': 'Effects Quality',
    'profile.effectsHigh': 'High',
    'profile.effectsMedium': 'Medium',
    'profile.effectsLow': 'Low',
    'profile.fontSize': 'Font Size',
    'profile.fontSmall': 'Small',
    'profile.fontMedium': 'Medium',
    'profile.fontLarge': 'Large',
    'profile.sfx': 'Sound Effects',
    'profile.bgMusic': 'Background Music',
    'profile.volume': 'Volume',
    'profile.highlightLastMove': 'Highlight Last Move',
    'profile.showWinningLine': 'Show Winning Line',
    'profile.pieceDropEffect': 'Piece Drop Effect',
    'profile.showHints': 'Show Hints',
    'profile.boardSkin': 'Board Skin',
    'profile.systemNotif': 'System Notifications',
    'profile.inviteNotif': 'Game Invites',
    'profile.chatNotif': 'Chat Messages',
    'profile.turnNotif': 'Turn Notifications',
    'profile.restoreDefaults': 'Restore Defaults',
    
    // Shop
    'shop.title': 'Shop',
    'shop.subtitle': 'Collect exclusive skins and items',
    'shop.coins': 'Coins',
    'shop.gems': 'Gems',
    'shop.featured': 'Featured',
    'shop.avatars': 'Avatar Frames',
    'shop.boardSkins': 'Board Skins',
    'shop.emotes': 'Emotes',
    'shop.buy': 'Buy',
    'shop.owned': 'Owned',
    'shop.equipped': 'Equipped',
    'shop.free': 'Free',
    'shop.needLogin': 'Login Required',
    'shop.loginMessage': 'Please login to purchase items.',
    'shop.notEnoughCurrency': 'Insufficient Funds',
    'shop.notEnoughCurrencyMessage': 'Not enough {currency} to buy this item.',
    'shop.confirmPurchase': 'Confirm Purchase',
    'shop.confirmPurchaseMessage': 'Are you sure you want to {action}?',
    'shop.purchaseSuccess': 'Purchase Successful!',
    'shop.purchaseSuccessMessage': 'Purchased {item}. Go to Inventory to use it!',
    'shop.purchaseFailed': 'Purchase Failed',
    'shop.loading': 'Loading...',
    'shop.breadcrumbShop': 'Shop',
    'shop.yourBalance': 'Your Balance',
    'shop.collection': 'Collection',
    
    // Quests
    'quests.title': 'Quests',
    'quests.subtitle': 'Complete quests for amazing rewards',
    'quests.daily': 'Daily',
    'quests.weekly': 'Weekly',
    'quests.achievements': 'Achievements',
    'quests.progress': 'Progress',
    'quests.claim': 'Claim',
    'quests.completed': 'Completed',
    'quests.claimed': 'Claimed',
    'quests.rewards': 'Rewards',
    'quests.exp': 'EXP',
    'quests.loading': 'Loading...',
    'quests.needLogin': 'Please login to view quests',
    'quests.levelProgress': 'Level Progress',
    'quests.currentLevel': 'Current Level',
    'quests.nextLevel': 'Next Level',
    'quests.expNeeded': 'EXP Needed',
    'quests.claimSuccess': 'Reward Claimed!',
    'quests.claimSuccessMessage': 'Received {coins} Coins{gems}!',
    'quests.difficultyEasy': 'Easy',
    'quests.difficultyMedium': 'Medium',
    'quests.difficultyHard': 'Hard',
    'quests.difficultyVeryHard': 'Very Hard',
    
    // Events
    'events.title': 'Events',
    'events.subtitle': 'Join events for amazing rewards',
    'events.current': 'Current',
    'events.upcoming': 'Upcoming',
    'events.past': 'Past',
    'events.joinNow': 'Join Now',
    'events.viewDetails': 'View Details',
    'events.loginEvent': 'Login Event',
    'events.loginEventDesc': 'Login daily to claim rewards',
    'events.matchEvent': 'Battle Event',
    'events.matchEventDesc': 'Play matches to earn Coins and Gems',
    'events.specialEvent': 'Special Event',
    'events.specialEventDesc': 'Hunt for huge Gems on weekends',
    'events.consecutiveLogins': 'Consecutive Logins',
    'events.todayMatches': 'Today\'s Matches',
    'events.day': 'Day',
    'events.matches': 'matches',
    'events.claimed': 'Claimed',
    'events.claimReward': 'Claim',
    'events.needLogin': 'Please login to join events',
    'events.loading': 'Loading...',
    'events.notEligible': 'You are not eligible for this reward yet!',
    'events.claimSuccess': 'Received {coins} Coins{gems}!',
    'events.claimFailed': 'Failed to claim reward!',
    'events.needMatches': 'You need to play',
    'events.dailyCheckin': 'Daily Check-in',
    'events.battleQuests': 'Battle Quests',
    'events.playMatches': 'Play {n} matches',
    'events.progress': 'Progress',
    'events.locked': 'Locked',
    'events.notEnough': 'Not enough',
    'events.preparing': 'Preparing...',
    'events.dayN': 'Day {n}',
    'events.aboutGems': 'About Gems',
    'events.aboutGemsDesc': 'Gems are premium currency for rare items and coin exchange.',
    
    // Guide
    'guide.title': 'Guide',
    'guide.subtitle': 'Learn and become a master',
    'guide.mainTitle': 'MASTERY MANUAL',
    'guide.mainSubtitle': 'Complete guide to Gomoku in MindPoint Arena',
    'guide.tableOfContents': 'Table of Contents',
    'guide.prevSection': 'Previous',
    'guide.nextSection': 'Next',
    'guide.compact': 'Compact',
    'guide.expand': 'Expand',
    'guide.viewMore': 'View more',
    'guide.intro': 'Introduction',
    'guide.rules': 'Game Rules',
    'guide.tactics': 'Basic Tactics',
    'guide.modes': 'Game Modes',
    'guide.progression': 'Progression System',
    'guide.advanced': 'Advanced Tips',
    'guide.faq': 'FAQ',
    'guide.breadcrumbGuide': 'Guide',
    'guide.menuIntro': 'Intro',
    'guide.menuRules': 'Rules',
    'guide.menuTactics': 'Tactics',
    'guide.menuModes': 'Modes',
    'guide.menuProgression': 'Progress',
    'guide.menuAdvanced': 'Advanced',
    'guide.menuFaq': 'FAQ',
    'guide.intro.subtitle1': 'Welcome seeker',
    'guide.intro.text1': 'I am the Elder guarding the path of Gomoku. Your journey of mastery begins.',
    'guide.intro.subtitle2': 'What is Gomoku?',
    'guide.intro.text2': 'A battle of patterns and foresight—each move advances your discipline.',
    'guide.intro.subtitle3': 'Your objective',
    'guide.intro.text3': 'Advance through realms by refining vision, timing, and resilience.',
    'guide.rules.subtitle1': 'Basic rule',
    'guide.rules.text1': 'Alternate placing stones; first to five in a line wins.',
    'guide.rules.subtitle2': 'Board sizes',
    'guide.rules.text2': 'Standard 15x15 favors rich strategy; larger boards reward deep planning.',
    'guide.rules.subtitle3': 'Time control',
    'guide.rules.text3': 'Turn and total clocks add pressure and reward precision.',
    'guide.rules.subtitle4': 'First-move pressure',
    'guide.rules.text4': 'Opening initiative must be converted into enduring threats.',
    'guide.tactics.subtitle1': 'Dual threat',
    'guide.tactics.text1': 'Create two simultaneous win threats forcing a single-block loss.',
    'guide.tactics.subtitle2': 'Active defense',
    'guide.tactics.text2': 'Balance attack with early interruption of opponent chains.',
    'guide.tactics.subtitle3': 'Center control',
    'guide.tactics.text3': 'Central stones multiply branching potential.',
    'guide.tactics.subtitle4': 'Deception',
    'guide.tactics.text4': 'Feign a line to misdirect while building the real win elsewhere.',
    'guide.tactics.subtitle5': 'Layered pressure',
    'guide.tactics.text5': 'Stack fallback threats to remain winning through blocks.',
    'guide.modes.subtitle1': 'AI training',
    'guide.modes.text1': 'Scale difficulty to sharpen pattern recognition before ranked.',
    'guide.modes.subtitle2': 'Casual play',
    'guide.modes.text2': 'Experiment freely without rating impact.',
    'guide.modes.subtitle3': 'Ranked arena',
    'guide.modes.text3': 'Earn rating—adapt or fall behind.',
    'guide.modes.subtitle4': 'Custom rooms',
    'guide.modes.text4': 'Tailored rules for focused practice or wagers.',
    'guide.modes.subtitle5': 'Tournaments',
    'guide.modes.text5': 'Structured competition with elevated rewards.',
    'guide.progression.subtitle1': 'Rating & ELO',
    'guide.progression.text1': 'More points beating stronger players; refine consistency.',
    'guide.progression.subtitle2': 'Coins & Gems',
    'guide.progression.text2': 'Soft vs premium currency—plan long term unlocks.',
    'guide.progression.subtitle3': 'Daily quests',
    'guide.progression.text3': 'Routine goals stabilize resource growth.',
    'guide.progression.subtitle4': 'Achievements',
    'guide.progression.text4': 'Milestones grant titles and bonus currency.',
    'guide.progression.subtitle5': 'Cosmetics',
    'guide.progression.text5': 'Express identity with board & piece skins.',
    'guide.advanced.subtitle1': 'AI review',
    'guide.advanced.text1': 'Surface missed optimal lines to accelerate learning.',
    'guide.advanced.subtitle2': 'Replay study',
    'guide.advanced.text2': 'Absorb elite opening structures & transitions.',
    'guide.advanced.subtitle3': 'Guild & friends',
    'guide.advanced.text3': 'Group practice compounds improvement.',
    'guide.advanced.subtitle4': 'Time management',
    'guide.advanced.text4': 'Swift evaluation keeps initiative.',
    'guide.advanced.subtitle5': 'Competitive mindset',
    'guide.advanced.text5': 'Detach from tilt; analyze instead of reacting.',
    'guide.faq.q1.title': 'How to rank up faster?',
    'guide.faq.q1.body': 'Play consistently, review losses, build streak momentum for bonus gains.',
    'guide.faq.q2.title': 'Do I lose coins on defeat?',
    'guide.faq.q2.body': 'No in casual. Only wager/custom rooms risk currency.',
    'guide.faq.q3.title': 'Is AI analysis accurate?',
    'guide.faq.q3.body': 'Trained on large expert datasets—high precision for standard boards.',
    'guide.faq.q4.title': 'Change username?',
    'guide.faq.q4.body': 'In Profile. First free, later changes cost Gems.',
    'guide.faq.q5.title': 'Fast Gem gain?',
    'guide.faq.q5.body': 'Weekly quests, hard achievements, tournaments, or purchase.',
    
    // Lobby
    'lobby.title': 'Lobby',
    'lobby.findMatch': 'Find Match',
    'lobby.createRoom': 'Create Room',
    'lobby.joinRoom': 'Join Room',
    'lobby.roomCode': 'Room Code',
    'lobby.searching': 'Searching...',
    'lobby.cancel': 'Cancel',
    
    // Inventory
    'inventory.title': 'Collection',
    'inventory.subtitle': 'Manage and use your owned items',
    'inventory.search': 'Search...',
    'inventory.filterType': 'Item Type',
    'inventory.filterRarity': 'Rarity',
    'inventory.filterStatus': 'Status',
    'inventory.all': 'All',
    'inventory.rarityCommon': 'Common',
    'inventory.rarityRare': 'Rare',
    'inventory.rarityEpic': 'Epic',
    'inventory.rarityLegendary': 'Legendary',
    'inventory.statusEquipped': 'Equipped',
    'inventory.statusUnequipped': 'Unequipped',
    'inventory.totalItems': 'Total Items',
    'inventory.breadcrumbHome': 'Main Hall',
    'inventory.breadcrumbInventory': 'Inventory',
    'inventory.yourCollection': 'Your Collection',
    'inventory.loading': 'Loading...',
    'inventory.pleaseLogin': 'Please login',
    'inventory.toViewCollection': 'to view your collection',
    'inventory.noItems': 'No items yet',
    'inventory.visitShop': 'Visit the shop to get items!',
    'inventory.goToShop': 'Go to Shop',
    'inventory.use': 'Use',
    'inventory.using': 'Equipped',
    'inventory.acquired': 'Acquired',
    'inventory.modalSuccess': 'Success',
    'inventory.modalError': 'Error',
    'inventory.modalNotification': 'Notification',
    'inventory.modalOk': 'OK',
    'inventory.errorPleaseLogin': 'Please login',
    'inventory.errorAlreadyEquipped': 'This item is already equipped',
    'inventory.successEquipped': 'Equipped',
    'inventory.errorCannotUse': 'Cannot use item',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.level': 'Level',
    'common.exp': 'Experience',
    'common.wins': 'Wins',
    'common.losses': 'Losses',
    'common.draws': 'Draws',
    'common.and': 'and',
    
    // Settings Popup
    'settings.title': 'Quick Settings',
    'settings.subtitle': 'Adjust sound & effects',
    'settings.sfx': 'Sound Effects',
    'settings.bgMusic': 'Background Music',
    'settings.notification': 'Notifications',
    'settings.language': 'Language',
    'settings.effects': 'Effects',
    'settings.effectsHigh': 'High',
    'settings.effectsMedium': 'Medium',
    'settings.effectsLow': 'Low',
    
    // Rank System
    'rank.label': 'Rank',
    'rank.vo_danh': 'Unranked',
    'rank.tan_ky': 'Novice',
    'rank.hoc_ky': 'Apprentice',
    'rank.ky_lao': 'Veteran',
    'rank.cao_ky': 'Master',
    'rank.ky_thanh': 'Grandmaster',
    'rank.truyen_thuyet': 'Legend',
    
    // Auth Landing
    'auth.landing.subtitle': 'Login or sign up to start your journey',
    'auth.landing.login': 'LOGIN',
    'auth.landing.signup': 'SIGN UP',
  },
  
  zh: {
      // Training modal
      'home.training.title': '修炼场',
      'home.training.subtitle': '选择机器人难度，先练后上分。',
      'home.training.nhapMon.title': '入门',
      'home.training.nhapMon.caption': '优先封堵强势手',
      'home.training.kyTai.title': '奇才',
      'home.training.kyTai.caption': '攻守平衡',
      'home.training.nghichThien.title': '逆天',
      'home.training.nghichThien.caption': '持续寻找进攻机会',
      'home.training.thienTon.title': '神境',
      'home.training.thienTon.caption': '预判2步',
      'home.training.huVo.title': '虚无',
      'home.training.huVo.caption': '预判3步',
      'home.training.difficultyEasy': '简单',
      'home.training.difficultyMedium': '中等',
      'home.training.difficultyHard': '困难',
      'home.training.difficultyVeryHard': '极难',
      'home.training.difficultyMaster': '大师',
      'home.training.createRoomBot': '创建房间并对战机器人',
    // Hotseat
    'hotseat.breadcrumb': '本地对战',
    'hotseat.title': '本地对战',
    'hotseat.subtitle': '一台设备双人',
    'hotseat.sideBlack': '黑子',
    'hotseat.sideWhite': '白子',
    'hotseat.turn': '回合',
    'hotseat.startNewRoundBlackFirst': '点击开始新局，黑先行。',
    'hotseat.nextTurn': '轮到{name}',
    'hotseat.winThisRound': '{name} 赢下本局！',
    'hotseat.timeOutWin': '{loser} 时间已尽。{winner} 赢下本局！',
    'hotseat.setupTitle': '对局设置',
    'hotseat.forbiddenRulesBlack': '黑禁手：三三 / 四四',
    'hotseat.timeLimit': '时间限制',
    'hotseat.timePerTurn': '每回合时间',
    'hotseat.seconds': '秒',
    'hotseat.swapSides': '交换双方',
    'hotseat.newRound': '新局',
    'hotseat.resetScores': '重置比分',
    'hotseat.postWinTitle': '本局结束',
    'hotseat.winThisRoundSuffix': '赢下本局！',
    'hotseat.review': '复盘',
    // Navigation
    'nav.home': '主页',
    'nav.lobby': '大厅',
    'nav.shop': '商店',
    'nav.profile': '档案',
    'nav.inventory': '背包',
    'nav.quests': '任务',
    'nav.events': '活动',
    'nav.guide': '指南',
    'nav.logout': '登出',
    
    // Breadcrumb
    'breadcrumb.home': '主殿',
    'breadcrumb.profile': '仙府',
    
    // Home Navigation (for mobile menu)
    'home.nav.shop': '商店',
    'home.nav.badgeHot': '热门',
    'home.nav.badgeNew': '新',
    'home.nav.badgeRank': '排位',
    'home.nav.inventory': '背包',
    'home.nav.quests': '任务',
    'home.nav.events': '活动',
    'home.nav.khaiNhan': '排位',
    'home.nav.guide': '指南',
    'home.nav.mentor': '复盘分析',
    
    // Home page
    'home.welcome': '欢迎来到Mindpoint Arena',
    'home.quickMatch': '快速匹配',
    'home.ranked': '排位赛',
    'home.training': '训练',
    'home.createRoom': '创建房间',
    'home.hotseat': '本地游戏',
    'home.onlinePlayers': '在线玩家',
    'home.rank': '等级',
    'home.winRate': '胜率',
    'home.totalMatches': '总场次',
    
    // Home Hero Section
    'home.hero.title': '从无名到无敌',
    'home.hero.subtitle': '立刻开局，日日精进 - 传奇从此刻开始',
    'home.hero.ctaQuickMatch': '快速匹配',
    'home.hero.ctaRankNote': '排位',
    
    // Home Game Modes
    'home.modes.ranked': '排位竞技场',
    'home.modes.tournament': '万门争锋',
    'home.modes.training': '修炼场',
    'home.modes.hotseat': '棋局对弈',
    

    
    // Home Events
    'home.events.thienCoBien.title': '天机变',
    'home.events.thienCoBien.subtitle': '大型锦标赛',
    'home.events.thienCoBien.chip': '特别',
    'home.events.thienCoBien.highlight': 'x2 Mindpoint奖励',
    'home.events.thienCoBien.timeline': '剩余3天',
    'home.events.thienCoBien.reward': '🏆 1000钻石',
    'home.events.thienCoBien.ctaLabel': '立即加入',
    'home.events.luaTraiDaiHoi.title': '篝火大会',
    'home.events.luaTraiDaiHoi.subtitle': '3v3团队战',
    'home.events.luaTraiDaiHoi.chip': '新',
    'home.events.luaTraiDaiHoi.highlight': '新游戏模式',
    'home.events.luaTraiDaiHoi.timeline': '剩余7天',
    'home.events.luaTraiDaiHoi.reward': '💎 500宝石+皮肤',
    'home.events.luaTraiDaiHoi.ctaLabel': '探索',
    'home.events.tuyetDinhSongDau.title': '巅峰对决',
    'home.events.tuyetDinhSongDau.subtitle': '1v1冠军赛',
    'home.events.tuyetDinhSongDau.chip': '排位',
    'home.events.tuyetDinhSongDau.highlight': 'x3排位速度',
    'home.events.tuyetDinhSongDau.timeline': '剩余5天',
    'home.events.tuyetDinhSongDau.reward': '⭐ 第1名: 2000宝石',
    'home.events.tuyetDinhSongDau.ctaLabel': '参战',
    
    // Home Social Tabs
    'home.social.friends': '道友',
    'home.social.chat': '传音',
    'home.social.info': '高人',
    
    // Home Friends
    'home.friends.title': '道友',
    'home.friends.connections': '{count}个连接',
    'home.friends.onlineCount': '{count}在线',
    'home.friends.loading': '加载中...',
    'home.friends.refresh': '🔄 刷新',
    'home.friends.searchPlaceholder': '🔍 搜索好友...',
    'home.friends.filterAll': '全部',
    'home.friends.filterOnline': '在线',
    'home.friends.filterIncoming': '收到邀请',
    'home.friends.filterOutgoing': '已发送',
    'home.friends.challenge': '挑战',
    'home.friends.daysAgo': '{count}天前',
    'home.friends.hoursAgo': '{count}小时前',
    'home.friends.minutesAgo': '{count}分钟前',
    'home.friends.justNow': '刚刚',
    'home.friends.hidden': '隐藏',
    'home.friends.anonymousUser': '匿名',
    'home.friends.anonymous': '无名',
    'home.friends.friendRequestSent': '{name}向您发送了好友请求',
    'home.friends.friendRequestAccepted': '{name}接受了您的请求',
    'home.friends.emptyStateAll': '还没有好友',
    'home.friends.emptyStateOnline': '没有在线好友',
    'home.friends.emptyStateIncoming': '没有收到邀请',
    'home.friends.emptyStateOutgoing': '没有发送邀请',
    
    // Profile
    'profile.overview': '棋迹',
    'profile.settings': '设置',
    'profile.history': '对战历史',
    'profile.totalGames': '总游戏数',
    'profile.settingsTitle': '设置',
    'profile.account': '账户',
    'profile.ui': '界面',
    'profile.sound': '声音',
    'profile.board': '棋盘与走棋',
    'profile.notifications': '通知',
    'profile.language': '语言',
    'profile.other': '其他',
    'profile.username': '用户名',
    'profile.email': '邮箱',
    'profile.changePassword': '更改密码',
    'profile.theme': '主题',
    'profile.themeDark': '暗色',
    'profile.themeLight': '亮色',
    'profile.uiEffects': 'UI效果',
    'profile.effectsQuality': '效果质量',
    'profile.effectsHigh': '高',
    'profile.effectsMedium': '中',
    'profile.effectsLow': '低',
    'profile.fontSize': '字体大小',
    'profile.fontSmall': '小',
    'profile.fontMedium': '中',
    'profile.fontLarge': '大',
    'profile.sfx': '音效',
    'profile.bgMusic': '背景音乐',
    'profile.volume': '音量',
    'profile.highlightLastMove': '高亮最后一步',
    'profile.showWinningLine': '显示获胜线',
    'profile.pieceDropEffect': '落子效果',
    'profile.showHints': '显示提示',
    'profile.boardSkin': '棋盘皮肤',
    'profile.systemNotif': '系统通知',
    'profile.inviteNotif': '游戏邀请',
    'profile.chatNotif': '聊天消息',
    'profile.turnNotif': '回合通知',
    'profile.restoreDefaults': '恢复默认',
    
    // Shop
    'shop.title': '商店',
    'shop.subtitle': '收集独特皮肤和物品',
    'shop.coins': '金币',
    'shop.gems': '宝石',
    'shop.featured': '精选',
    'shop.avatars': '头像框',
    'shop.boardSkins': '棋盘皮肤',
    'shop.emotes': '表情',
    'shop.buy': '购买',
    'shop.owned': '已拥有',
    'shop.equipped': '使用中',
    'shop.free': '免费',
    'shop.needLogin': '需要登录',
    'shop.loginMessage': '请登录以购买物品。',
    'shop.notEnoughCurrency': '余额不足',
    'shop.notEnoughCurrencyMessage': '{currency}不足以购买此物品。',
    'shop.confirmPurchase': '确认购买',
    'shop.confirmPurchaseMessage': '确定要{action}吗？',
    'shop.purchaseSuccess': '购买成功！',
    'shop.purchaseSuccessMessage': '已购买{item}。前往背包使用！',
    'shop.purchaseFailed': '购买失败',
    'shop.loading': '加载中...',
    'shop.breadcrumbShop': '商店',
    'shop.yourBalance': '你的余额',
    'shop.collection': '收藏',
    
    // Quests
    'quests.title': '任务',
    'quests.subtitle': '完成任务获得丰厚奖励',
    'quests.daily': '每日',
    'quests.weekly': '每周',
    'quests.achievements': '成就',
    'quests.progress': '进度',
    'quests.claim': '领取',
    'quests.completed': '已完成',
    'quests.claimed': '已领取',
    'quests.rewards': '奖励',
    'quests.exp': '经验',
    'quests.loading': '加载中...',
    'quests.needLogin': '请登录以查看任务',
    'quests.levelProgress': '等级进度',
    'quests.currentLevel': '当前等级',
    'quests.nextLevel': '下一级',
    'quests.expNeeded': '所需经验',
    'quests.claimSuccess': '领取奖励成功！',
    'quests.claimSuccessMessage': '获得{coins}金币{gems}！',
    'quests.difficultyEasy': '简单',
    'quests.difficultyMedium': '中等',
    'quests.difficultyHard': '困难',
    'quests.difficultyVeryHard': '非常困难',
    
    // Events
    'events.title': '活动',
    'events.subtitle': '参加活动获得丰厚奖励',
    'events.current': '进行中',
    'events.upcoming': '即将到来',
    'events.past': '已结束',
    'events.joinNow': '立即参加',
    'events.viewDetails': '查看详情',
    'events.loginEvent': '登录活动',
    'events.loginEventDesc': '每日登录领取奖励',
    'events.matchEvent': '对战活动',
    'events.matchEventDesc': '参与对战赚取金币和宝石',
    'events.specialEvent': '特别活动',
    'events.specialEventDesc': '周末狂欢赢取巨额宝石',
    'events.consecutiveLogins': '连续登录',
    'events.todayMatches': '今日对战',
    'events.day': '天',
    'events.matches': '场',
    'events.claimed': '已领取',
    'events.claimReward': '领取',
    'events.needLogin': '请登录以参加活动',
    'events.loading': '加载中...',
    'events.notEligible': '您还不符合领取此奖励的条件！',
    'events.claimSuccess': '获得{coins}金币{gems}！',
    'events.claimFailed': '领取奖励失败！',
    'events.needMatches': '您需要进行',
    'events.dailyCheckin': '每日签到',
    'events.battleQuests': '战斗任务',
    'events.playMatches': '进行{n}场对局',
    'events.progress': '进度',
    'events.locked': '未解锁',
    'events.notEnough': '未达到',
    'events.preparing': '准备中...',
    'events.dayN': '第{n}天',
    'events.aboutGems': '关于宝石',
    'events.aboutGemsDesc': '宝石是高级货币，用于购买稀有物品和兑换金币。',
    
    // Guide
    'guide.title': '指南',
    'guide.subtitle': '学习并成为高手',
    'guide.mainTitle': '天机秘典',
    'guide.mainSubtitle': 'MindPoint Arena 五子棋完全指南',
    'guide.tableOfContents': '目录',
    'guide.prevSection': '上一节',
    'guide.nextSection': '下一节',
    'guide.compact': '精简',
    'guide.expand': '展开',
    'guide.viewMore': '查看更多',
    'guide.intro': '简介',
    'guide.rules': '游戏规则',
    'guide.tactics': '基本战术',
    'guide.modes': '游戏模式',
    'guide.progression': '进阶系统',
    'guide.advanced': '高级技巧',
    'guide.faq': '常见问题',
    'guide.breadcrumbGuide': '指南',
    'guide.menuIntro': '简介',
    'guide.menuRules': '规则',
    'guide.menuTactics': '战术',
    'guide.menuModes': '模式',
    'guide.menuProgression': '进阶',
    'guide.menuAdvanced': '高级',
    'guide.menuFaq': 'FAQ',
    'guide.intro.subtitle1': '欢迎新棋者',
    'guide.intro.text1': '我是守护五子棋道的长老，你的修炼之旅已开启。',
    'guide.intro.subtitle2': '五子棋是什么？',
    'guide.intro.text2': '它是前瞻与格局的博弈，每一步都是修行。',
    'guide.intro.subtitle3': '你的目标',
    'guide.intro.text3': '不断提升洞察与节奏，跨越更高层次。',
    'guide.rules.subtitle1': '基本规则',
    'guide.rules.text1': '轮流落子，先成五连者胜。',
    'guide.rules.subtitle2': '棋盘尺寸',
    'guide.rules.text2': '标准15x15最常见，越大越考验规划。',
    'guide.rules.subtitle3': '时间控制',
    'guide.rules.text3': '限制单步与总时长增加对局压力。',
    'guide.rules.subtitle4': '先手压力',
    'guide.rules.text4': '先手须构筑优势，否则易被反制。',
    'guide.tactics.subtitle1': '双重威胁',
    'guide.tactics.text1': '制造两处同时成五机会逼迫对手失守。',
    'guide.tactics.subtitle2': '主动防守',
    'guide.tactics.text2': '进攻同时预判并截断对手潜在四连。',
    'guide.tactics.subtitle3': '中心控制',
    'guide.tactics.text3': '中心位拥有更多延展方向。',
    'guide.tactics.subtitle4': '诱敌',
    'guide.tactics.text4': '伪装威胁转移注意力在他处完成布局。',
    'guide.tactics.subtitle5': '层压进攻',
    'guide.tactics.text5': '多层后备威胁保证持续获胜机会。',
    'guide.modes.subtitle1': 'AI训练',
    'guide.modes.text1': '按难度提升模式识别与判断。',
    'guide.modes.subtitle2': '休闲对局',
    'guide.modes.text2': '不影响积分，适合实验。',
    'guide.modes.subtitle3': '排位赛',
    'guide.modes.text3': '胜负改变积分，检验实力。',
    'guide.modes.subtitle4': '自定义房间',
    'guide.modes.text4': '自由设定规则与节奏。',
    'guide.modes.subtitle5': '锦标赛',
    'guide.modes.text5': '高层次奖励与竞争。',
    'guide.progression.subtitle1': '积分与等级',
    'guide.progression.text1': '战胜强者涨分多，保持稳定性。',
    'guide.progression.subtitle2': '金币与宝石',
    'guide.progression.text2': '普通与稀有货币分工不同。',
    'guide.progression.subtitle3': '每日任务',
    'guide.progression.text3': '稳定资源获取节奏。',
    'guide.progression.subtitle4': '成就系统',
    'guide.progression.text4': '里程碑奖励称号与货币。',
    'guide.progression.subtitle5': '外观装饰',
    'guide.progression.text5': '棋盘与棋子皮肤彰显个性。',
    'guide.advanced.subtitle1': 'AI复盘',
    'guide.advanced.text1': '发现错失最佳走法加速提升。',
    'guide.advanced.subtitle2': '对局学习',
    'guide.advanced.text2': '吸收高手开局与转换策略。',
    'guide.advanced.subtitle3': '好友与公会',
    'guide.advanced.text3': '团队训练提升效率。',
    'guide.advanced.subtitle4': '时间管理',
    'guide.advanced.text4': '快速评估保持主动权。',
    'guide.advanced.subtitle5': '心态',
    'guide.advanced.text5': '避免情绪化，客观复盘。',
    'guide.faq.q1.title': '怎样更快提升段位?',
    'guide.faq.q1.body': '持续对局+复盘+连胜奖励加速涨分。',
    'guide.faq.q2.title': '失败会失去金币吗?',
    'guide.faq.q2.body': '休闲模式不扣，只有下注房间有风险。',
    'guide.faq.q3.title': 'AI分析准确吗?',
    'guide.faq.q3.body': '大规模高手数据训练，标准盘精度高。',
    'guide.faq.q4.title': '如何改用户名?',
    'guide.faq.q4.body': '在资料页，首次免费，之后消耗宝石。',
    'guide.faq.q5.title': '快速获取宝石?',
    'guide.faq.q5.body': '周任务、难成就、赛事或购买。',
    
    // Lobby
    'lobby.title': '大厅',
    'lobby.findMatch': '寻找对手',
    'lobby.createRoom': '创建房间',
    'lobby.joinRoom': '加入房间',
    'lobby.roomCode': '房间代码',
    'lobby.searching': '搜索中...',
    'lobby.cancel': '取消',
    
    // Inventory
    'inventory.title': '收藏',
    'inventory.subtitle': '管理和使用已拥有的物品',
    'inventory.search': '搜索...',
    'inventory.filterType': '物品类型',
    'inventory.filterRarity': '稀有度',
    'inventory.filterStatus': '状态',
    'inventory.all': '全部',
    'inventory.rarityCommon': '普通',
    'inventory.rarityRare': '稀有',
    'inventory.rarityEpic': '史诗',
    'inventory.rarityLegendary': '传说',
    'inventory.statusEquipped': '已装备',
    'inventory.statusUnequipped': '未装备',
    'inventory.totalItems': '总物品',
    'inventory.breadcrumbHome': '主厅',
    'inventory.breadcrumbInventory': '背包',
    'inventory.yourCollection': '你的收藏',
    'inventory.loading': '加载中...',
    'inventory.pleaseLogin': '请登录',
    'inventory.toViewCollection': '查看你的收藏',
    'inventory.noItems': '还没有物品',
    'inventory.visitShop': '去商店购买物品！',
    'inventory.goToShop': '去商店',
    'inventory.use': '使用',
    'inventory.using': '已装备',
    'inventory.acquired': '获得',
    'inventory.modalSuccess': '成功',
    'inventory.modalError': '错误',
    'inventory.modalNotification': '通知',
    'inventory.modalOk': '确定',
    'inventory.errorPleaseLogin': '请登录',
    'inventory.errorAlreadyEquipped': '该物品已装备',
    'inventory.successEquipped': '已装备',
    'inventory.errorCannotUse': '无法使用物品',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.yes': '是',
    'common.no': '否',
    'common.ok': '确定',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.level': '等级',
    'common.exp': '经验',
    'common.wins': '胜',
    'common.losses': '败',
    'common.draws': '平',
    
    // Settings Popup
    'settings.title': '快速设置',
    'settings.subtitle': '调整声音和效果',
    'settings.sfx': '音效',
    'settings.bgMusic': '背景音乐',
    'settings.notification': '通知',
    'settings.language': '语言',
    'settings.effects': '效果',
    'settings.effectsHigh': '高',
    'settings.effectsMedium': '中',
    'settings.effectsLow': '低',
    
    // Rank System
    'rank.label': '境界',
    'rank.vo_danh': '无名',
    'rank.tan_ky': '新手',
    'rank.hoc_ky': '学士',
    'rank.ky_lao': '棋老',
    'rank.cao_ky': '高手',
    'rank.ky_thanh': '棋圣',
    'rank.truyen_thuyet': '传奇',
    
    // Auth Landing
    'auth.landing.subtitle': '登录或注册开始游戏',
    'auth.landing.login': '登录',
    'auth.landing.signup': '注册',
  },
  
  ja: {
      // Training modal
      'home.training.title': '修練場',
      'home.training.subtitle': 'ランク前にボット難易度で練習しよう。',
      'home.training.nhapMon.title': '入門',
      'home.training.nhapMon.caption': '強い手を優先してブロック',
      'home.training.kyTai.title': '奇才',
      'home.training.kyTai.caption': '攻守バランス',
      'home.training.nghichThien.title': '逆天',
      'home.training.nghichThien.caption': '常に攻めを狙う',
      'home.training.thienTon.title': '神境',
      'home.training.thienTon.caption': '2手先読み',
      'home.training.huVo.title': '虚無',
      'home.training.huVo.caption': '3手先読み',
      'home.training.difficultyEasy': '易',
      'home.training.difficultyMedium': '普',
      'home.training.difficultyHard': '難',
      'home.training.difficultyVeryHard': '激難',
      'home.training.difficultyMaster': '達人',
      'home.training.createRoomBot': '部屋を作って対局(ボット)',
    // Hotseat
    'hotseat.breadcrumb': 'ローカル対局',
    'hotseat.title': 'ローカル対局',
    'hotseat.subtitle': '1台の端末で2人対局',
    'hotseat.sideBlack': '黒',
    'hotseat.sideWhite': '白',
    'hotseat.turn': '手番',
    'hotseat.startNewRoundBlackFirst': 'タップして新局開始、黒が先手。',
    'hotseat.nextTurn': '{name} の手番',
    'hotseat.winThisRound': '{name} の勝ち！',
    'hotseat.timeOutWin': '{loser} の持ち時間切れ。{winner} の勝ち！',
    'hotseat.setupTitle': '対局設定',
    'hotseat.forbiddenRulesBlack': '黒の禁手：三三／四四',
    'hotseat.timeLimit': '持ち時間',
    'hotseat.timePerTurn': '1手あたりの時間',
    'hotseat.seconds': '秒',
    'hotseat.swapSides': '先後入れ替え',
    'hotseat.newRound': '新局',
    'hotseat.resetScores': 'スコアをリセット',
    'hotseat.postWinTitle': '対局終了',
    'hotseat.winThisRoundSuffix': 'の勝ち！',
    'hotseat.review': '検討',
    // Navigation
    'nav.home': 'ホーム',
    'nav.lobby': 'ロビー',
    'nav.shop': 'ショップ',
    'nav.profile': 'プロフィール',
    'nav.inventory': 'インベントリ',
    'nav.quests': 'クエスト',
    'nav.events': 'イベント',
    'nav.guide': 'ガイド',
    'nav.logout': 'ログアウト',
    
    // Breadcrumb
    'breadcrumb.home': '本殿',
    'breadcrumb.profile': '仙府',
    
    // Home Navigation (for mobile menu)
    'home.nav.shop': 'ショップ',
    'home.nav.badgeHot': '人気',
    'home.nav.badgeNew': '新',
    'home.nav.badgeRank': 'ランク',
    'home.nav.inventory': 'インベントリ',
    'home.nav.quests': 'クエスト',
    'home.nav.events': 'イベント',
    'home.nav.khaiNhan': 'ランク',
    'home.nav.guide': 'ガイド',
    'home.nav.mentor': 'リプレイ分析',
    
    // Home page
    'home.welcome': 'Mindpoint Arenaへようこそ',
    'home.quickMatch': 'クイックマッチ',
    'home.ranked': 'ランクマッチ',
    'home.training': 'トレーニング',
    'home.createRoom': 'ルーム作成',
    'home.hotseat': 'ローカルプレイ',
    'home.onlinePlayers': 'オンラインプレイヤー',
    'home.rank': 'ランク',
    'home.winRate': '勝率',
    'home.totalMatches': '総試合数',
    
    // Home Hero Section
    'home.hero.title': '無名から無敵へ',
    'home.hero.subtitle': '今すぐプレイ、毎日上達 - 伝説はここから始まる',
    'home.hero.ctaQuickMatch': 'クイックマッチ',
    'home.hero.ctaRankNote': 'ランク',
    
    // Home Game Modes
    'home.modes.ranked': 'ランクアリーナ',
    'home.modes.tournament': '万門争覇',
    'home.modes.training': '修練場',
    'home.modes.hotseat': 'ローカル対局',
    
    // Home Events
    'home.events.thienCoBien.title': '天機変',
    'home.events.thienCoBien.subtitle': '大規模トーナメント',
    'home.events.thienCoBien.chip': '特別',
    'home.events.thienCoBien.highlight': 'x2 Mindpoint報酬',
    'home.events.thienCoBien.timeline': '残り3日',
    'home.events.thienCoBien.reward': '🏆 1000ダイヤモンド',
    'home.events.thienCoBien.ctaLabel': '今すぐ参加',
    'home.events.luaTraiDaiHoi.title': 'キャンプファイア集会',
    'home.events.luaTraiDaiHoi.subtitle': '3v3チームバトル',
    'home.events.luaTraiDaiHoi.chip': '新規',
    'home.events.luaTraiDaiHoi.highlight': '新ゲームモード',
    'home.events.luaTraiDaiHoi.timeline': '残り7日',
    'home.events.luaTraiDaiHoi.reward': '💎 500ジェム+スキン',
    'home.events.luaTraiDaiHoi.ctaLabel': '探索',
    'home.events.tuyetDinhSongDau.title': '究極の決闘',
    'home.events.tuyetDinhSongDau.subtitle': '1v1チャンピオンシップ',
    'home.events.tuyetDinhSongDau.chip': 'ランク',
    'home.events.tuyetDinhSongDau.highlight': 'x3ランク速度',
    'home.events.tuyetDinhSongDau.timeline': '残り5日',
    'home.events.tuyetDinhSongDau.reward': '⭐ 1位: 2000ジェム',
    'home.events.tuyetDinhSongDau.ctaLabel': '参戦',
    
    // Home Social Tabs
    'home.social.friends': '道友',
    'home.social.chat': '伝音',
    'home.social.info': '高人',
    
    // Home Friends
    'home.friends.title': 'フレンド',
    'home.friends.connections': '{count}接続',
    'home.friends.onlineCount': '{count}オンライン',
    'home.friends.loading': '読み込み中...',
    'home.friends.refresh': '🔄 更新',
    'home.friends.searchPlaceholder': '🔍 フレンド検索...',
    'home.friends.filterAll': 'すべて',
    'home.friends.filterOnline': 'オンライン',
    'home.friends.filterIncoming': '受信リクエスト',
    'home.friends.filterOutgoing': '送信済み',
    'home.friends.challenge': 'チャレンジ',
    'home.friends.daysAgo': '{count}日前',
    'home.friends.hoursAgo': '{count}時間前',
    'home.friends.minutesAgo': '{count}分前',
    'home.friends.justNow': 'たった今',
    'home.friends.hidden': '非表示',
    'home.friends.anonymousUser': '匿名',
    'home.friends.anonymous': '無名',
    'home.friends.friendRequestSent': '{name}があなたにフレンドリクエストを送信しました',
    'home.friends.friendRequestAccepted': '{name}があなたのリクエストを承認しました',
    'home.friends.emptyStateAll': 'まだフレンドがいません',
    'home.friends.emptyStateOnline': 'オンラインのフレンドがいません',
    'home.friends.emptyStateIncoming': '受信リクエストなし',
    'home.friends.emptyStateOutgoing': '送信リクエストなし',
    
    // Profile
    'profile.overview': '棋跡',
    'profile.settings': '設定',
    'profile.history': '対戦履歴',
    'profile.totalGames': '総ゲーム数',
    'profile.settingsTitle': '設定',
    'profile.account': 'アカウント',
    'profile.ui': 'インターフェース',
    'profile.sound': 'サウンド',
    'profile.board': 'ボードと動き',
    'profile.notifications': '通知',
    'profile.language': '言語',
    'profile.other': 'その他',
    'profile.username': 'ユーザー名',
    'profile.email': 'メール',
    'profile.changePassword': 'パスワード変更',
    'profile.theme': 'テーマ',
    'profile.themeDark': 'ダーク',
    'profile.themeLight': 'ライト',
    'profile.uiEffects': 'UIエフェクト',
    'profile.effectsQuality': 'エフェクト品質',
    'profile.effectsHigh': '高',
    'profile.effectsMedium': '中',
    'profile.effectsLow': '低',
    'profile.fontSize': 'フォントサイズ',
    'profile.fontSmall': '小',
    'profile.fontMedium': '中',
    'profile.fontLarge': '大',
    'profile.sfx': '効果音',
    'profile.bgMusic': 'BGM',
    'profile.volume': '音量',
    'profile.highlightLastMove': '最後の手をハイライト',
    'profile.showWinningLine': '勝利ラインを表示',
    'profile.pieceDropEffect': 'ピース配置エフェクト',
    'profile.showHints': 'ヒントを表示',
    'profile.boardSkin': 'ボードスキン',
    'profile.systemNotif': 'システム通知',
    'profile.inviteNotif': 'ゲーム招待',
    'profile.chatNotif': 'チャットメッセージ',
    'profile.turnNotif': 'ターン通知',
    'profile.restoreDefaults': 'デフォルトに戻す',
    
    // Shop
    'shop.title': 'ショップ',
    'shop.subtitle': '限定スキンとアイテムを集める',
    'shop.coins': 'コイン',
    'shop.gems': 'ジェム',
    'shop.featured': '注目',
    'shop.avatars': 'アバターフレーム',
    'shop.boardSkins': 'ボードスキン',
    'shop.emotes': 'エモート',
    'shop.buy': '購入',
    'shop.owned': '所有',
    'shop.equipped': '装備中',
    'shop.free': '無料',
    'shop.needLogin': 'ログインが必要',
    'shop.loginMessage': 'アイテムを購入するにはログインしてください。',
    'shop.notEnoughCurrency': '残高不足',
    'shop.notEnoughCurrencyMessage': '{currency}が不足しています。',
    'shop.confirmPurchase': '購入確認',
    'shop.confirmPurchaseMessage': '{action}してもよろしいですか？',
    'shop.purchaseSuccess': '購入成功！',
    'shop.purchaseSuccessMessage': '{item}を購入しました。インベントリで使用できます！',
    'shop.purchaseFailed': '購入失敗',
    'shop.loading': '読み込み中...',
    'shop.breadcrumbShop': 'ショップ',
    'shop.yourBalance': '残高',
    'shop.collection': 'コレクション',
    
    // Quests
    'quests.title': 'クエスト',
    'quests.subtitle': 'クエストをクリアして豪華報酬をゲット',
    'quests.daily': 'デイリー',
    'quests.weekly': 'ウィークリー',
    'quests.achievements': '実績',
    'quests.progress': '進行状況',
    'quests.claim': '受け取る',
    'quests.completed': '完了',
    'quests.claimed': '受取済み',
    'quests.rewards': '報酬',
    'quests.exp': '経験値',
    'quests.loading': '読み込み中...',
    'quests.needLogin': 'クエストを見るにはログインしてください',
    'quests.levelProgress': 'レベル進行状況',
    'quests.currentLevel': '現在のレベル',
    'quests.nextLevel': '次のレベル',
    'quests.expNeeded': '必要経験値',
    'quests.claimSuccess': '報酬を受け取りました！',
    'quests.claimSuccessMessage': '{coins}コイン{gems}を獲得！',
    'quests.difficultyEasy': '簡単',
    'quests.difficultyMedium': '普通',
    'quests.difficultyHard': '難しい',
    'quests.difficultyVeryHard': '非常に難しい',
    
    // Events
    'events.title': 'イベント',
    'events.subtitle': 'イベントに参加して豪華報酬をゲット',
    'events.current': '開催中',
    'events.upcoming': '近日開催',
    'events.past': '終了',
    'events.joinNow': '今すぐ参加',
    'events.viewDetails': '詳細を見る',
    'events.loginEvent': 'ログインイベント',
    'events.loginEventDesc': '毎日ログインして報酬をゲット',
    'events.matchEvent': 'バトルイベント',
    'events.matchEventDesc': '対戦してコインとジェムを獲得',
    'events.specialEvent': '特別イベント',
    'events.specialEventDesc': '週末に巨額ジェムをゲット',
    'events.consecutiveLogins': '連続ログイン',
    'events.todayMatches': '今日の対戦',
    'events.day': '日',
    'events.matches': '試合',
    'events.claimed': '受取済み',
    'events.claimReward': '受け取る',
    'events.needLogin': 'イベントに参加するにはログインしてください',
    'events.loading': '読み込み中...',
    'events.notEligible': 'まだこの報酬を受け取る条件を満たしていません！',
    'events.claimSuccess': '{coins}コイン{gems}を獲得！',
    'events.claimFailed': '報酬の受け取りに失敗しました！',
    'events.needMatches': 'プレイが必要',
    'events.dailyCheckin': 'デイリーログイン',
    'events.battleQuests': 'バトルクエスト',
    'events.playMatches': '{n}試合をプレイ',
    'events.progress': '進捗',
    'events.locked': '未開放',
    'events.notEnough': '不足',
    'events.preparing': '準備中...',
    'events.dayN': '{n}日目',
    'events.aboutGems': 'ジェムについて',
    'events.aboutGemsDesc': 'ジェムはレアアイテム購入やコイン交換に使うプレミアム通貨です。',
    
    // Guide
    'guide.title': 'ガイド',
    'guide.subtitle': '学んでマスターになろう',
    'guide.mainTitle': '天機秘典',
    'guide.mainSubtitle': 'MindPoint Arena 五目並べ完全ガイド',
    'guide.tableOfContents': '目次',
    'guide.prevSection': '前へ',
    'guide.nextSection': '次へ',
    'guide.compact': 'コンパクト',
    'guide.expand': '展開',
    'guide.viewMore': 'もっと見る',
    'guide.intro': 'イントロダクション',
    'guide.rules': 'ゲームルール',
    'guide.tactics': '基本戦術',
    'guide.modes': 'ゲームモード',
    'guide.progression': '進行システム',
    'guide.advanced': '上級テクニック',
    'guide.faq': 'よくある質問',
    'guide.breadcrumbGuide': 'ガイド',
    'guide.menuIntro': 'イントロ',
    'guide.menuRules': 'ルール',
    'guide.menuTactics': '戦術',
    'guide.menuModes': 'モード',
    'guide.menuProgression': '進行',
    'guide.menuAdvanced': '上級',
    'guide.menuFaq': 'FAQ',
    'guide.intro.subtitle1': '新たな挑戦者へ',
    'guide.intro.text1': 'ここは五目並べの道。あなたの修練が始まる。',
    'guide.intro.subtitle2': '五目並べとは?',
    'guide.intro.text2': '先読みと構築の芸術。全ての一手が鍛錬。',
    'guide.intro.subtitle3': '目的',
    'guide.intro.text3': '洞察と速度と安定を極め、段階的に昇華する。',
    'guide.rules.subtitle1': '基本ルール',
    'guide.rules.text1': '交互に石を置き五連先取で勝利。',
    'guide.rules.subtitle2': '盤サイズ',
    'guide.rules.text2': '15x15が標準。大盤は深い計画力必須。',
    'guide.rules.subtitle3': '持ち時間',
    'guide.rules.text3': '手番時間と総時間で緊張感を高める。',
    'guide.rules.subtitle4': '先手の重み',
    'guide.rules.text4': '先手は主導権を継続的脅威に転換すべき。',
    'guide.tactics.subtitle1': '二重脅威',
    'guide.tactics.text1': '同時勝ち筋で相手に単一防御を強要。',
    'guide.tactics.subtitle2': '能動防御',
    'guide.tactics.text2': '攻めつつ危険ラインを早期遮断。',
    'guide.tactics.subtitle3': '中心支配',
    'guide.tactics.text3': '中心は分岐経路が豊富。',
    'guide.tactics.subtitle4': '陽動',
    'guide.tactics.text4': '偽の脅威で注意を逸らし本筋構築。',
    'guide.tactics.subtitle5': '層状プレッシャー',
    'guide.tactics.text5': '複数予備勝ち筋で防御後も勝勢維持。',
    'guide.modes.subtitle1': 'AI訓練',
    'guide.modes.text1': '難易度調整で認識力強化。',
    'guide.modes.subtitle2': 'カジュアル',
    'guide.modes.text2': 'レート非影響で試行。',
    'guide.modes.subtitle3': 'ランク戦',
    'guide.modes.text3': '勝敗がレートに反映。',
    'guide.modes.subtitle4': 'カスタム部屋',
    'guide.modes.text4': '設定自由で集中練習。',
    'guide.modes.subtitle5': 'トーナメント',
    'guide.modes.text5': '高報酬の競技環境。',
    'guide.progression.subtitle1': 'レート & ELO',
    'guide.progression.text1': '強者撃破で高増加。安定性が鍵。',
    'guide.progression.subtitle2': 'コイン & ジェム',
    'guide.progression.text2': '入手難度と用途が異なる通貨。',
    'guide.progression.subtitle3': 'デイリー',
    'guide.progression.text3': '資源獲得リズムを維持。',
    'guide.progression.subtitle4': '実績',
    'guide.progression.text4': '節目で称号と報酬。',
    'guide.progression.subtitle5': '外観',
    'guide.progression.text5': '盤と駒のスキンで個性表現。',
    'guide.advanced.subtitle1': 'AI解析',
    'guide.advanced.text1': '最善手逸脱を特定して改善。',
    'guide.advanced.subtitle2': 'リプレイ学習',
    'guide.advanced.text2': '上級者の構築と転換を吸収。',
    'guide.advanced.subtitle3': 'ギルド & フレンド',
    'guide.advanced.text3': '共同練習で加速。',
    'guide.advanced.subtitle4': '時間管理',
    'guide.advanced.text4': '迅速評価で主導権維持。',
    'guide.advanced.subtitle5': 'メンタル',
    'guide.advanced.text5': '連敗でも冷静に分析。',
    'guide.faq.q1.title': '素早くランクを上げるには?',
    'guide.faq.q1.body': '継続対局+復盤+連勝ボーナス活用。',
    'guide.faq.q2.title': '敗北でコインは減る？',
    'guide.faq.q2.body': 'カジュアルは減らない。賭け部屋のみリスク。',
    'guide.faq.q3.title': 'AI解析は正確？',
    'guide.faq.q3.body': '大規模データで高精度（標準盤）。',
    'guide.faq.q4.title': 'ユーザー名変更方法？',
    'guide.faq.q4.body': 'プロフィールで。初回無料、以後ジェム消費。',
    'guide.faq.q5.title': 'ジェム高速入手？',
    'guide.faq.q5.body': '週クエ・高難度実績・大会・購入。',
    
    // Lobby
    'lobby.title': 'ロビー',
    'lobby.findMatch': 'マッチを探す',
    'lobby.createRoom': 'ルーム作成',
    'lobby.joinRoom': 'ルーム参加',
    'lobby.roomCode': 'ルームコード',
    'lobby.searching': '検索中...',
    'lobby.cancel': 'キャンセル',
    
    // Inventory
    'inventory.title': 'コレクション',
    'inventory.subtitle': '所有しているアイテムを管理・使用',
    'inventory.search': '検索...',
    'inventory.filterType': 'アイテムタイプ',
    'inventory.filterRarity': 'レア度',
    'inventory.filterStatus': '状況',
    'inventory.all': '全て',
    'inventory.rarityCommon': 'コモン',
    'inventory.rarityRare': 'レア',
    'inventory.rarityEpic': 'エピック',
    'inventory.rarityLegendary': 'レジェンド',
    'inventory.statusEquipped': '装備中',
    'inventory.statusUnequipped': '未装備',
    'inventory.totalItems': '総アイテム数',
    'inventory.breadcrumbHome': '本殿',
    'inventory.breadcrumbInventory': 'インベントリ',
    'inventory.yourCollection': 'あなたのコレクション',
    'inventory.loading': '読み込み中...',
    'inventory.pleaseLogin': 'ログインしてください',
    'inventory.toViewCollection': 'コレクションを表示する',
    'inventory.noItems': 'アイテムがありません',
    'inventory.visitShop': 'ショップでアイテムを購入しましょう！',
    'inventory.goToShop': 'ショップへ',
    'inventory.use': '使用',
    'inventory.using': '装備中',
    'inventory.acquired': '取得',
    'inventory.modalSuccess': '成功',
    'inventory.modalError': 'エラー',
    'inventory.modalNotification': '通知',
    'inventory.modalOk': 'OK',
    'inventory.errorPleaseLogin': 'ログインしてください',
    'inventory.errorAlreadyEquipped': 'このアイテムはすでに装備されています',
    'inventory.successEquipped': '装備しました',
    'inventory.errorCannotUse': 'アイテムを使用できません',
    
    // Common
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.close': '閉じる',
    'common.yes': 'はい',
    'common.no': 'いいえ',
    'common.ok': 'OK',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.level': 'レベル',
    'common.exp': '経験値',
    'common.wins': '勝利',
    'common.losses': '敗北',
    'common.draws': '引き分け',
    'common.and': 'と',
    
    // Settings Popup
    'settings.title': 'クイック設定',
    'settings.subtitle': 'サウンドとエフェクトを調整',
    'settings.sfx': '効果音',
    'settings.bgMusic': '背景音楽',
    'settings.notification': '通知',
    'settings.language': '言語',
    'settings.effects': 'エフェクト',
    'settings.effectsHigh': '高',
    'settings.effectsMedium': '中',
    'settings.effectsLow': '低',
    
    // Rank System
    'rank.label': '境界',
    'rank.vo_danh': '無名',
    'rank.tan_ky': '初心者',
    'rank.hoc_ky': '学士',
    'rank.ky_lao': 'ベテラン',
    'rank.cao_ky': '高手',
    'rank.ky_thanh': '棋聖',
    'rank.truyen_thuyet': '伝説',
    
    // Auth Landing
    'auth.landing.subtitle': 'ログインまたは登録してゲームを始める',
    'auth.landing.login': 'ログイン',
    'auth.landing.signup': '登録',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language
    return saved || 'vi'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    document.documentElement.setAttribute('lang', lang)
    
    // Dispatch event để đồng bộ với các component khác
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }))
  }

  const t = (key: string, params?: Record<string, any>): string => {
    // Attempt order:
    // 1. Exact flat key in current language (legacy map)
    // 2. Exact flat key in English
    // 3. Nested traversal in current language (i18n.json)
    // 4. Nested traversal in English
    // 5. Fallback: last segment THEN full key
    let text: string | undefined

    // 1 & 2: flat lookup even if key contains dots
    const flatCurrent = translations[language]?.[key]
    if (flatCurrent) text = flatCurrent
    if (!text) {
      const flatEn = translations['en']?.[key]
      if (flatEn) text = flatEn
    }

    // 3 & 4: nested lookup only if not found flat
    if (!text && key.includes('.')) {
      const keys = key.split('.')
      const traverse = (lang: Language): string | undefined => {
        let current: any = i18nTranslations[lang]
        for (const k of keys) {
          if (current && typeof current === 'object' && k in current) {
            current = current[k]
          } else {
            return undefined
          }
        }
        return typeof current === 'string' ? current : undefined
      }
      text = traverse(language) || traverse('en')

      if (!text) {
        // 5: fallback last segment; if too generic return full key
        const last = keys[keys.length - 1]
        text = last.length <= 2 ? key : last
      }
    }

    if (!text) {
      // Final fallback if key had no dots
      text = key
    }

    // Parameter replacement
    if (params) {
      Object.keys(params).forEach(param => {
        text = text!.replace(new RegExp(`\\{${param}\\}`, 'g'), String(params[param]))
      })
    }
    return text
  }

  useEffect(() => {
    // Đặt ngôn ngữ ban đầu
    document.documentElement.setAttribute('lang', language)
    
    // Lắng nghe sự kiện languageChanged từ các component khác (như Profile settings)
    const handleLanguageChange = (event: CustomEvent) => {
      const newLang = event.detail as Language
      if (newLang && newLang !== language) {
        setLanguageState(newLang)
        localStorage.setItem('language', newLang)
        document.documentElement.setAttribute('lang', newLang)
      }
    }
    
    window.addEventListener('languageChanged', handleLanguageChange as EventListener)
    
    return () => {
      window.removeEventListener('languageChanged', handleLanguageChange as EventListener)
    }
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
